### ISSUE TITLE
Crashes gnome-shell with large album art

### ISSUE THREAD

**Issue by bwat47** [eonpatapon/gnome-shell-extensions-mediaplayer#121]
I've noticed a problem where it seems if there is a very large album art image the media player indicator will completely crash gnome-shell (and not just a restart crash, it makes you log out and disables all extensions) as soon as you start playing a song from that album in a media player. I saw the issue in both fedora 18 and arch linux with gnome 3.6 with both rhythmbox and clementine.

Here's the image that was causing the crash for me, when I replaced the folder.jpg with a smaller image I was able to play the album without crashing:

![folder](https://f.cloud.github.com/assets/1442520/225819/09371a66-8607-11e2-9917-6d934a97f0bd.jpg)

**Comment by eonpatapon** [comment]
Please try the extension from the devel branch if you are still using it :-)

**Comment by Eeemil** [comment]
Had similar issue in #177 , the problem has been fixed in devel branch.

**Comment by eonpatapon** [comment]
Fixed in master
