### ISSUE TITLE
Online Accounts status wrong after locking the screen with extension enabled

### ISSUE THREAD

**Issue by SietsevanderMolen** [eonpatapon/gnome-shell-extensions-mediaplayer#130]
Using this extension on Gnome 3.8.1 triggers this bug:

https://bugzilla.gnome.org/show_bug.cgi?id=700168

You might have to try to lock/unlock two or three times in case it doesn't show up at first
Also if the allow to start media player option is enabled it creates an infinite time of launchers over time.

**Comment by eonpatapon** [comment]
3.8 is now very old. I close the issue
