### ISSUE TITLE
Gnome 3.10 integration

### ISSUE THREAD

**Issue by jbreizh** [eonpatapon/gnome-shell-extensions-mediaplayer#143]
Here a mock up of 3.10 integration amelioration: don't know if it can be done.
Keep up the good work
![mockup](https://f.cloud.github.com/assets/2498942/1434180/eb3ab198-410f-11e3-832e-4bba54c7b570.png)

**Comment by eonpatapon** [comment]
I created a 'menu-redesign' branch to implement this

**Comment by jbreizh** [comment]
Hello,
i try it (menu-redesign branch ) and i like the style (but it's not a news...) : the integration is way better with 3.10+ menu. I have a few observations : 
- i think the icon must be at the left and not the right of the menu
- the extension doesn't work well at the moment but i suppose it's ok due to the devel status

Anyway have you decide if it was just a test or it will be the futur design of the extension ?
Thanks and have a nice day

**Comment by eonpatapon** [comment]
You should use the master branch now, it's not a test anymore ;)
