### ISSUE TITLE
Song titles with < in name do not display in menu bar, possible tag injection issue?

### ISSUE THREAD

**Issue by micolous** [eonpatapon/gnome-shell-extensions-mediaplayer#155]
[Song titles containing `<`](http://musicbrainz.org/search?query=%3C&type=recording&method=indexed) not display correctly in the menu bar, instead, no text is displayed at all, and only the album art icon appears.

I'm using the extension with Banshee, and the following configuration:

- Appearance: `Current album cover`
- Status text: `%a - %t`

The titles appear correctly in the menu pop-up.

The help text for the status text setting states that Pango mark-up is supported, so I suspect that the status text from the media player is not escaped before being substituted into this string.

This could also be a problem for network streams, as they could have Pango mark-up injected into the stream metadata.  I don't think there's a way to execute code with Pango mark-up, at worst, a network stream could change the text size to something huge and mess up the layout of the menu bar.

**Comment by JasonLG1979** [comment]
#289 Fixes this.
