### ISSUE TITLE
Can't click music player to start it

### ISSUE THREAD

**Issue by brefan** [eonpatapon/gnome-shell-extensions-mediaplayer#161]
Hi,

I'm trying to get quodlibet integrated into the sound menu. I couldn't select quodlibet as the default player in gnome, so I added an entry to `.local/share/applications/mimeapps.list`. With that out of the way I set `com.canonical.indicator.sound preferred-media-players` to `['quodlibet']`.
The result is, that quodlibet shows up in the sound indicator menu, but I can only start it by clicking the cogs icon next to the text. I'd like to be able to hover over and click the text to start it.
Also, once quodlibet is started, everything works as expected.

**Comment by eonpatapon** [comment]
UI changed since, closing this.
