### ISSUE TITLE
Needs a 'repeat all/repeat single' toggle

### ISSUE THREAD

**Issue by i30817** [eonpatapon/gnome-shell-extensions-mediaplayer#164]
The play list support is nice but sometimes i hit a song i really enjoy and want it to keep playing and then i have to pull up the app.

**Comment by JasonLG1979** [comment]
What you're looking for is LoopStatus:
https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:LoopStatus

We can try to set LoopStatus but it's an optional Property and I'm not sure how many or if any players support it? There's no way for us to *make* a player do anything really. It depends on their implementation of the MPRIS2 interface. It can be though of as a server client relationship. The player is the server, they create the interface, we are the client, we use their interface. What we can do depends on their interface and what they make available on their interface, and if their interface is implemented correctly.

**Comment by i30817** [comment]
That's fine, but there aren't that many players surely? You can test it out and whitelist those that do support it to show the widget you end up with.

**Comment by JasonLG1979** [comment]
> That's fine, but there aren't that many players surely?

Are you serious? There are more music player than I can count,lol!!!

> You can test it out and whitelist those that do support it to show the widget you end up with.

That's a big NO. I'm not going to test EVERY music player. It's not my job to test every player against the extension to make sure it works. That's the point of the spec. We follow the spec, if a player follows the spec it will work. My point is that even if we expose this functionality we may very well end up end up with loop buttons that do nothing for 99% of the players out there because the property is optional.

**Comment by JasonLG1979** [comment]
What I can do is try to find a place to put in in the UI and make it an optional if it's shown or not(defaulting to not shown) again if the buttons actually do anything will depend on if the player supports the feature. Does that work for you?

**Comment by JasonLG1979** [comment]
From the spec the possible values are:
"None" if the playback will stop when there are no more tracks to play
"Track" if the current track will start again from the begining once it has finished playing
"Playlist" if the playback loops through a list of tracks

**Comment by i30817** [comment]
> Does that work for you?
Sure.

**Comment by JasonLG1979** [comment]
Ok I'm working on it now. Should have something here in a bit.

**Comment by JasonLG1979** [comment]
Looking at the source code of various players I've only found 2(Banshee and Exaile) that actually expose the ability to set the property. If you would like to add the feature you're more than welcome to but I'm not going to spend my time on a feature that only works with a couple players. sorry.

**Comment by JasonLG1979** [comment]
Closing this for now. As I've said I don't plan on ever implementing this personally. If anyone else wants to do the work a PR is welcome.
