### ISSUE TITLE
Multiple entries of closed/stopped players remains on the menu

### ISSUE THREAD

**Issue by oguzhanogreden** [eonpatapon/gnome-shell-extensions-mediaplayer#165]
As it is apparent in the attached screenshot, many instances of same or different players remain on the dropdown menu even though they are closed. Clicking x's nearby each one does not help.
![screenshot from 2014-06-04 20 55 12](https://cloud.githubusercontent.com/assets/7797029/3177564/782a548a-ec11-11e3-9139-d6721c00064f.png)

**Comment by eonpatapon** [comment]
Should be fixed in recent builds
