### ISSUE TITLE
Volume control of Spotify not working

### ISSUE THREAD

**Issue by grubersjoe** [eonpatapon/gnome-shell-extensions-mediaplayer#168]
Arch Linux, Gnome 3.12.3, Pulse Audio, [Spotify from AUR](https://aur.archlinux.org/packages/spotify/), latest version of extension

I'm not sure, whether this is a problem of my specific system or it is simply is not supported, but I'm unable to adjust the volume of Spotify through the extension. The volume bar is set to the minimum and adjusting its level has no effect.

Of course not a crucial feature, but nive to have. Do you think this is possible? Or does Spotify simply not support this?

PS: Awesome extension, keep up the good work!

**Comment by InfernoZeus** [comment]
Relevant issue on Spotify's support site: https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/MPRIS2-and-volume/td-p/87145
I've bumped it but I have absolutely no confidence in the "amazing" Spotify team to fix it.
