### ISSUE TITLE
Feature request: optionally prepend track number to track name?

### ISSUE THREAD

**Issue by nommer** [eonpatapon/gnome-shell-extensions-mediaplayer#170]
Users who play classical music, audiobooks, or other long multi-track works
normally played in sequence would likely find it useful to see the
the number of the track currently playing added to the track name, e.g.,

                   410 - Va, ma soeur, l'implorer
                   by Hector Berlioz
                   from Les Troyens

This could help them to sense where they are in the course of a long series
of tracks. No doubt many users would prefer not to see the track number, so probably best implemented as an option in prefs.

**Comment by rrthomas** [comment]
Would love this!

**Comment by eonpatapon** [comment]
This is now possible using the master branch. Explained in the README

**Comment by rrthomas** [comment]
Thanks very much for this, and in particular the README example showing how to use it! Works great.
