### ISSUE TITLE
Panel icon not updating

### ISSUE THREAD

**Issue by franziskuskiefer** [eonpatapon/gnome-shell-extensions-mediaplayer#172]
The album cover in the panel does not get updated. Not sure when it gets set,  but while playing around with the extension settings it changes. But as soon as one cover is set it seems never to change. The album cover is set correct in the extensions drop down, but not in the panel.
![meidaplayerscreenshot](https://cloud.githubusercontent.com/assets/890105/4119273/5915b47a-32a9-11e4-8dc5-dc28224c94c7.png)

**Comment by eonpatapon** [comment]
Don't think it's still valid with the code in master. I you can test it

**Comment by eonpatapon** [comment]
Fixed in master
