### ISSUE TITLE
Extension must add a scrollbar to menu

### ISSUE THREAD

**Issue by kelunik** [eonpatapon/gnome-shell-extensions-mediaplayer#175]
This extension doesn't add a scrollbar if the menu gets too high. Gnome developers said, extensions are responsible for that, see bug report there: https://bugzilla.gnome.org/show_bug.cgi?id=735979

Screenshot: ![Screenshot](https://bug735979.bugzilla-attachments.gnome.org/attachment.cgi?id=285268)

**Comment by eonpatapon** [comment]
Related to #143

**Comment by eonpatapon** [comment]
Fixed in master branch
