### ISSUE TITLE
GNOME Shell goes FUBAR when using Clementine with Media Player Indicator

### ISSUE THREAD

**Issue by Eeemil** [eonpatapon/gnome-shell-extensions-mediaplayer#177]
Description:
While starting a track in Clementine while using the latest version Media Player Indicator (as of 14:th September, 2014) in Ubuntu, GNOME Shell somehow crashes, all icons and text becomes unrecognizeable.
![screenshot from 2014-09-13 23 12 57](https://cloud.githubusercontent.com/assets/7189109/4262165/49f80902-3b91-11e4-9212-70da8e135979.png)
Using:
* GNOME Shell 3.10.4
* Clementine 1.2
* Ubuntu 14.04

Reproduction:
1.) Start Clementine.
2.) Start a song, either through Clementine's interface, or through Media Player Indicator.

Additional notes:
* The error does not occur while using Rhythmbox
* When GNOME Shell has entered the FUBAR-state, it is still responsive and useable. If font size and icon theme is changed in gnome-tweak-tools, the shell almost returns to normal, and the error does not occur again if clementine is further used.
* I am not sure if the error is in Media Player Indicator, Clementine or GNOME Shell or some other things.
* I have used Clementine with Media Player Indicator before
* No error occurs when running Clementine without Media Player Indicator.
* When running Clementine from a terminal, it generates the following text on startup:
  * 00:22:43.587 WARN  unknown                          "sni-qt/5235" WARN  00:22:43.587 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE  
  * 00:22:43.748 WARN  unknown                          QDBusConnection: name 'org.freedesktop.UDisks' had owner '' but we thought it was ':1.101'

**Comment by eonpatapon** [comment]
Im now using Gio.FileIcon to render covers in the extension. You can try the code in the devel branch.

I've made a test with your cover and it works well here.

**Comment by eonpatapon** [comment]
Related to #121

**Comment by Eeemil** [comment]
I can verify that devel branch code fixes this issue. Thanks!
