### ISSUE TITLE
DeaDBeeF did not recognized by the extension

### ISSUE THREAD

**Issue by MCommander** [eonpatapon/gnome-shell-extensions-mediaplayer#185]
Hi,

use DeaDBeeF 0.6.2 with Arch and Gnome 3.14.2.

The Extension ist only shown three gears, nothing more. With for example audacious it works just fine.

Anyone knows why?

Best Regards

MCommander

**Comment by grawity** [comment]
Have you installed and enabled the "DeaDBeeF-MPRIS" plugin? The extension requires MPRISv2, it will not use other APIs.

What does `gdbus introspect -e -d org.mpris.MediaPlayer2.deadbeef -o /org/mpris/MediaPlayer2` print?

**Comment by MCommander** [comment]
In the AUR i found the deadbeef-mpris2-plugin 1.7-1

https://github.com/Serranya/deadbeef-mpris2-plugin

This Version seems to work quite well.

Thanks a lot for the tip!
