### ISSUE TITLE
Control from lock screen

### ISSUE THREAD

**Issue by martijnatema** [eonpatapon/gnome-shell-extensions-mediaplayer#187]
I would love to see the option to view the playing song and control it from the lock screen.

**Comment by grawity** [comment]
I don't think gnome-shell allows extensions to run at all while locked, does it?

**Comment by martijnatema** [comment]
Wouldn't it be possible to create a persistent notification?

**Comment by grawity** [comment]
Persistent notifications are only useful if there's something that can react to signals from button clicks... and if the extensions are unloaded when locking, they can't do this.

**Comment by martijnatema** [comment]
That's too bad, then
