### ISSUE TITLE
Not working on Ubuntu Gnome 14.10 with Gnome 3.14

### ISSUE THREAD

**Issue by jonnius** [eonpatapon/gnome-shell-extensions-mediaplayer#188]
OS: Ubuntu Gnome 14.10 with updated Gnome Shell (3.14.3)

The extension shows up in the menu but does not show media controls of banshee when banshee is running. lg shows this:

Error: No signal connection function () {
    [sourceless code]
} found

**Comment by eonpatapon** [comment]
Do you have enabled the MPRIS2 plugin in banshee ?

**Comment by eonpatapon** [comment]
Even if it's for the Ubuntu sound menu you can follow this guide : http://www.omgubuntu.co.uk/2010/09/how-to-enable-banshee-sound-menu-integration-in-ubuntu-10-10

**Comment by jonnius** [comment]
I did everything like explained ther. I have enabled the Plugin that is called MPRIS D-Bus Interface in Banshee. Back in time it was already working when I used Ubuntu 14.04 with Gnome 3.10...

**Comment by eonpatapon** [comment]
Can you check with d-feet on the session bus if org.mpris.MediaPlayer2.banshee is available ?

**Comment by jonnius** [comment]
I checked it and it is availabe. What about the error of mentioned in my first post?

**Comment by eonpatapon** [comment]
Check the .xsession-errors log instead if there is anything meaningful

**Comment by jonnius** [comment]
I cannot find that file. It should be located in home folder, right?

**Comment by eonpatapon** [comment]
Yes but it's not the same location on every distribution...

Alternatively you can run gnome-shell --replace in a terminal. You'll see all
the logs in it. Run banshee then, paste the log somewhere so I can have a look.

**Comment by jonnius** [comment]
So finally I did. I appended the terminal output of gnome-shell while 
the extension was enabled and banshee was playing music...

Am 27.02.2015 um 12:36 schrieb Jean-Philippe Braun:

**Comment by jonnius** [comment]
I don't know what has changed, but now it is working fine. I hope the 
issue won't return...

Am 09.03.2015 um 18:16 schrieb J. Zeidler:

**Comment by eonpatapon** [comment]
Well that's good news then!
