### ISSUE TITLE
"Unable to locate package gnome-shell-extensions-mediaplayer" - UbuntuGnome 14.04

### ISSUE THREAD

**Issue by alexxtasi** [eonpatapon/gnome-shell-extensions-mediaplayer#190]
Hi 
I have this problem when trying to install  gnome-shell-extensions-mediaplayer using the ppa as described in the README file "Ubuntu - [webupd8 PPA](http://www.webupd8.org/2011/10/gnome-shell-mediaplayer-extension.html)".
The problem is that at the 3rd step the message ``` E: Unable to locate package gnome-shell-extensions-mediaplayer ``` comes up.
any suggestions ?

thank you in advance

**Comment by eonpatapon** [comment]
I don't know about this repo. Maybe you can install the extension from http://extensions.gnome.org.
