### ISSUE TITLE
Make the play/pause button bigger etc.

### ISSUE THREAD

**Issue by matejak** [eonpatapon/gnome-shell-extensions-mediaplayer#191]
The most used functions should be accessible more easily, the potentially fatal ones should be, on the contrary, less accessible.
Therefore, I suggest to make the play/pause button bigger, so navigating to it is easier and faster.
Similarly, I suggest moving the stop button to the rightmost position. Clicking it is difficult to undo and I think that it is rarely used.

**Comment by JasonLG1979** [comment]
Stop is not "fatal". Quit would be the closest thing to fatal you could get for a media player.(the extension currently does not have a quit button) But from a design standpoint rearranging the buttons from the pretty much universally understood order they are currently in is not a good idea and would lead to a greater likelihood that the user clicking the wrong button.
