### ISSUE TITLE
Some PropertiesChanged signals are lost when sent in succession

### ISSUE THREAD

**Issue by jdoe0** [eonpatapon/gnome-shell-extensions-mediaplayer#194]
When a media player sends multiple org.freedesktop.DBus.Properties.PropertiesChanged signal multiple times in rapid succession right after starting up, some of the signals sent are lost, which can result in inconsistent state between the media player and the extension. This is caused by the "hack to avoid the trackBox.box.get_stage() == null" introduced in fccbd1b. Reverting the commit fixes the problem.

**Comment by eonpatapon** [comment]
Hi,

I don't really understand the relation between this commit and your problem. Can you explain how to reproduce your issue ?

Thanks a lot

**Comment by jdoe0** [comment]
I'm able to reproduce the issue with [gnome-mpv](https://github.com/gnome-mpv/gnome-mpv). When the player is started by double-clicking on some file (usually an audio file with metadata), the extension shows the playback status as "stopped" though the file is actually being played. This doesn't occur if the the file is opened manually after the player is launched. [mpristester](https://github.com/randomguy3/mpristester/) correctly shows the playback status as "playing" even when opening a file by double-clicking.

**Comment by eonpatapon** [comment]
Completely rewrite the code of the extension in the devel branch.

I can't reproduce this issue with the new code. Maybe you can confirm.

**Comment by jdoe0** [comment]
I can confirm that the issue is not reproducible with the new code in devel. Also, the issue is no longer reproducible in master.

Thanks for your work!

**Comment by eonpatapon** [comment]
Thanks for testing
