### ISSUE TITLE
Does not work with latest version of Spotify (1.0.7.*)

### ISSUE THREAD

**Issue by HJGreen** [eonpatapon/gnome-shell-extensions-mediaplayer#196]
The most recent builds of Spotify (>1.0.*) are not detected by the extension.

Tested on Ubuntu 15.04, with Gnome 3.16.2
Spotify version: 1.0.7.153.gb9e8174a
Available here: https://www.spotify.com/uk/download/linux/

**Comment by grawity** [comment]
I think that's because Spotify dropped MPRIS support, no?

Run D-Feet or `dbus-monitor --session` and check if Spotify registers any bus names.

**Comment by HJGreen** [comment]
[Ah, yes](https://community.spotify.com/t5/Spotify-Announcements/Spotify-Client-1-x-beta-for-Linux-has-been-released/m-p/1147714#M7279). Should hopefully be reintroduced in future versions.
