### ISSUE TITLE
Media button icon sizes

### ISSUE THREAD

**Issue by zagortenay333** [eonpatapon/gnome-shell-extensions-mediaplayer#198]
I noticed you hard-coded the icon size in the media button *(pause, play next..)* to 20px. The actual size of the icons used is 16px though. This makes them appear slightly blurry.

Any chance of fixing it?

**Comment by eonpatapon** [comment]
Are you using another theme because in the default I think it is scalable icons that are used.

**Comment by zagortenay333** [comment]
Yes they are scalabe, but scalable doesn't mean you should scale or that it will look nice. This is especially true at small sizes. They will only appear properly crisp on 16px or some really big number.

**Comment by eonpatapon** [comment]
I'll check the difference. But IIRC I tried and I found it too small

**Comment by zagortenay333** [comment]
Well it's a personal preference kinda thingy. I kinda don't like them blurry :smile:

**Comment by eonpatapon** [comment]
![capture du 2015-07-22 20-16-52](https://cloud.githubusercontent.com/assets/418227/8833512/60e0edc8-30af-11e5-9b99-8ee7937692d5.png)

**Comment by zagortenay333** [comment]
Thx. Looks way better to me.
