### ISSUE TITLE
Spotify is no more supported

### ISSUE THREAD

**Issue by efposadac** [eonpatapon/gnome-shell-extensions-mediaplayer#199]
The extension is not working with Spotify version 1.0.9.133. Tested on Debian testing distro.

**Comment by grawity** [comment]
Yes, see #196.

**Comment by efposadac** [comment]
Oh I see, I am sorry...

**Comment by eonpatapon** [comment]
I'm sorry for you :)

**Comment by eonpatapon** [comment]
I'll let the issue open until spotify reintroduce MPRIS support

**Comment by linuxman94** [comment]
New version of Spotify was released today with dbus/mpris support.  The application ID is  com.spotify.music instead of com.spotify.qt

https://community.spotify.com/t5/Spotify-Announcements/Spotify-beta-1-0-13-for-Linux-released/td-p/1197675

**Comment by grawity** [comment]
The application ID doesn't matter. Apps can own multiple "service names" on DBus, so MPRIS2 implementations always claim a `org.mpris.MediaPlayer2.*` in addition to their regular one.

Does Spotify do that? If so, it should show up in the player list automatically.

**Comment by linuxman94** [comment]
Ah I understand now. Still kind of learning dbus stuff.

It shows up in the player list, but it's broken.  I shows unknown for all track info fields.

**Comment by grawity** [comment]
I'm not _entirely_ sure how the extension even retrieves data initially. Try `dbus-monitor --session path=/org/mpris/MediaPlayer2`. Does it send out "PropertiesChanged"s correctly? How well do [mpris][2] and [mpristester][1] work with it?

[1]: https://github.com/randomguy3/mpristester/
[2]: https://github.com/grawity/hacks/blob/master/media/mpris

**Comment by linuxman94** [comment]
mpris works fine.  I'm not sure if Spotify is sending the PropertiesChanged correctly.  dbus-monitor doesn't output anything when I skip tracks in spotify

**Comment by linuxman94** [comment]
I left a comment in the linux beta thread on the Spotify forums.  They're usually pretty responsive.

**Comment by eonpatapon** [comment]
The player needs to send new metadatas with the PropertiesChanged signal on track change: https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/player.js#L210

**Comment by eonpatapon** [comment]
At start the extension just get the Metadata property directly to populate the UI:  https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/player.js#L277

**Comment by eonpatapon** [comment]
Anyway seems in your case that the PropertiesChanged signal is not sent.

**Comment by linuxman94** [comment]
The devs are looking into sending the PropertiesChanged signal

https://community.spotify.com/t5/Spotify-Announcements/Spotify-beta-1-0-13-for-Linux-released/m-p/1198759#M7993

**Comment by qmarlats** [comment]
Anything new about this bug? It would be very cool to have track infos :notes:

**Comment by grawity** [comment]
From what I've heard, Spotify regained some MPRISv2 support, with bugs however. For example, it doesn't implement o.f.DBus.Properties.GetAll(), even though it supports Get() fine.

**Comment by SalahAdDin** [comment]
This problem haven't yer solved, now i have a problem with Spotify.

The media player indicator can't show the track, and line don't move, the buttons works but the other no!
![area de trabajo 1_073](https://cloud.githubusercontent.com/assets/5034215/12865721/4a9a90ea-cc82-11e5-8e81-dbf06bae9cd6.png)

**Comment by qmarlats** [comment]
Yep this is the same problem since Spotify 1.x, only the three buttons are working... I hope it will be resolved, but for the moment there are no changes even on Arch with the latest version (1.0.23)

**Comment by berarma** [comment]
I guess it would help voting for this thread with the "Me too" button: https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/Linux-Spotify-DBus-MPRIS2-support-not-fully-working/td-p/1208249/highlight/false
