### ISSUE TITLE
Position and appearance in statusArea

### ISSUE THREAD

**Issue by archdria** [eonpatapon/gnome-shell-extensions-mediaplayer#200]
First of all, thank for the update, I love the new version.

I think it would be good if we could choose where to place the icon in the statusArea.
Currently it is placed to the right-most position (from extension.js):
``` let indicatorIndex = Main.panel.statusArea.aggregateMenu._indicators.get_children().length - 1;```
However, I prefer it to be in the first position, so I edited it to be
 ```let indicatorIndex = 0;```

Am I the only one to prefer it in this position ?

Finally, could it be possible to use the symbolic icon, so that it fits better with other icons in the Menu?

Thank you :)

**Comment by eonpatapon** [comment]
I can put it in the first position, I don't mind.

About the symbolic icon, yes I wanted to be able to have a symbolic icon. Will work on that too

**Comment by archdria** [comment]
Great, thank you!

It also looks that we lost the close button with the new design, was that on purpose?

**Comment by eonpatapon** [comment]
Yes it was lost, because I don't know where to put it anymore
