### ISSUE TITLE
Possibility to hide icon

### ISSUE THREAD

**Issue by michael-rapp** [eonpatapon/gnome-shell-extensions-mediaplayer#202]
I recently updated the extension to Git revision 3.10.r502 via AUR. Since then, there is always an icon/album art showing up in the top panel, even when integrating it into the volume menu. There seems to be no option to hide the icon in the appearance settings. I would really appreciate such a possibility, because I don't want to see an icon in the panel permanently.

**Comment by eonpatapon** [comment]
You have the default player in the menu I assume ?

**Comment by michael-rapp** [comment]
I don't know what you are meaning exactly. I use Rhythmbox as my media player. Maybe the attached screenshot shows what is going on...
![bildschirmfoto von 2015-08-10 14-44-10](https://cloud.githubusercontent.com/assets/6638695/9171802/c702b956-3f6e-11e5-90cb-87b5cb5414bc.png)

**Comment by eonpatapon** [comment]
Ok, that's the normal behaviour, but the spacing with other icons is weird.

Not sure if I will add such option though.

**Comment by michael-rapp** [comment]
I would have expected the icon to be only visible when not being integrated into the existing menu. If it is expected behavior like you say, I would really like to have an option to hide it. It wasn't visible in earlier versions and I really liked it as it was. All other aspects of the re-design are gorgeous anyways.

**Comment by eonpatapon** [comment]
The point was to have the same behaviour as other indicators of the aggregate menu (icon visible when feature is on or off)

**Comment by michael-rapp** [comment]
I understand this argument. Maybe the icon should only be shown when music is currently playing? Like for example the VPN icon, which is only visible when a VPN connection is currently active.

**Comment by eonpatapon** [comment]
Agreed

**Comment by ianbrunelli** [comment]
It would be nice if the icon could be merged with the volume, as both are on the same category. Maybe adding the state ("pause", "play", "stop") indicator on the corner of the volume.

**Comment by eonpatapon** [comment]
Honnestly it's quite dirty and painful to do things like that :)

**Comment by michael-rapp** [comment]
I tested out the changes, which have been introduced by solving this issue and to be honest I expected a slightly different behavior. When the media player application is not running at all, the extension's icon in the system menu is gone, which is nice. But when the application is started, the icon immediately appears, though there is still no music playing. Also, when starting the playback and stopping it again (not pausing it) the icon remains visible. I would have expected the icon to be only visible when the music is playing or paused, no when it is stopped. My music player application is always running in the background so I can listen to music without having the window opened. So the behavior, which has been introduced with this issue, does not change anything at all, because the application is always running in background and therefore the icon is always visible. Is there a good reason why the icon should not be hidden when playback is stopped?

**Comment by eonpatapon** [comment]
Yes, so you can middle click on it to play.

**Comment by eonpatapon** [comment]
Showing the icon to notify there is a player running is the main reason.

**Comment by michael-rapp** [comment]
I wasn't aware of this feature ;-) However, I think this issue is a matter of taste. I just wanted you to know, that I had a different thing in mind, when I opened this issue. Nevertheless the changes are an improvement, althought I still don't like the icon to always hang around in my panel. I guess I will just patch it out of my local installation. Thank you for considering my comments.

**Comment by eonpatapon** [comment]
It's always about taste and it's difficult to find the sweet spot. For now I will leave it like this, but this can change in the future.

You can also scroll up/down on the icon to change tracks ;-)
