### ISSUE TITLE
icon is appearing outside of the system menu

### ISSUE THREAD

**Issue by lostson** [eonpatapon/gnome-shell-extensions-mediaplayer#208]
icon is appearing outside of the system menu, pretty much self explanatory. I have it set to appear in the system menu but it appears just outside of it to the left. I am using Debian Jessie with Gnome 3.14. 
![screenshot from 2015-09-30 11 24 32](https://cloud.githubusercontent.com/assets/4975802/10199364/f644edc8-6765-11e5-927a-b53b2b1c0480.png)

**Comment by MatatTHC** [comment]
With a recent update an extra icon has been added. I liked the previous state where it integrated nicely in the system indicator. Would be great to have an option to configure this. 

Anyway: Thank you for the efforts you put in this nice extension.

**Comment by eonpatapon** [comment]
@MatatTHC please open another issue.

This issue is due to a CSS problem but 3.14 is old now.

**Comment by brinox** [comment]
I'm encountering this probem, too, using the latest Git revision of the extension in GNOME 3.18 on Arch Linux. It seems that this bug does also appear on newer versions of GNOME.

**Comment by eonpatapon** [comment]
![screenshot from 2015-10-16 13-43-44](https://cloud.githubusercontent.com/assets/418227/10540863/4aed7df6-740c-11e5-97d4-d61aa63264f3.png)

Seems fine for me here on 3.18

**Comment by brinox** [comment]
I think you're getting it wrong: We'd like to have **either** the icon in the system bar **x**or the panel in the system menu. The icon should not appear in the system bar, when all the stuff is display in the menu instead.

**Comment by eonpatapon** [comment]
Yes this is the normal behaviour now. The indicator icon is now shown when the player is active like other indicators (wifi, vpn etc...).
