### ISSUE TITLE
Extra Icon

### ISSUE THREAD

**Issue by MatatTHC** [eonpatapon/gnome-shell-extensions-mediaplayer#209]
With a recent update an extra icon has been added. I liked the previous state where it integrated nicely in the system indicator. Would be great to have an option to configure this.

Anyway: Thank you for the efforts you put in this nice extension.
![screenshot from 2015-10-05 11 03 38](https://cloud.githubusercontent.com/assets/2079496/10276605/c730900c-6b50-11e5-8041-56d3287f34bf.png)

**Comment by badcel** [comment]
I also liked it better when no icon was shown if it integrated into the system menu. For example there is also a bluetooth icon in the system menu but it's not shown in the indicators.

**Comment by eonpatapon** [comment]
Showing the icon when the player is playing but not when it's stopped would be fine ?

**Comment by badcel** [comment]
Yes. I think this behaviour would better apply to the pattern used by the other indicators. I also checked the new Gnome HIG guidelines but did not find further information regarding indicators.

**Comment by badcel** [comment]
An example: If I'm connected to a wireless lan the wifi symbol is shown as indicator. But if i start a vpn connection over this wifi, the wifi symbol is removed and the vpn symbol is shown.

I think the intention of the gnome developers is to keep the indicators as clean as possible (gnomes "stay out of the way" philosophy). As the playing of music is directly connected to the system volume, perhaps it should be somhow integrated?

**Comment by eonpatapon** [comment]
It's not related directly to the system volume and the icon provides functionnality like middle click to play/pause and scroll up/down to change tracks
