### ISSUE TITLE
Album art not updating with Pandora/Pithos

### ISSUE THREAD

**Issue by dkogias** [eonpatapon/gnome-shell-extensions-mediaplayer#212]
Fedora 22, streaming Pandora wtih [Pithos](https://github.com/pithos/pithos):

After updating the extension via extensions.gnome.org, album art no longer updates when Pandora starts the next track.

**Comment by dkogias** [comment]
Update: Locking the screen and unlocking forces the album art to update.

**Comment by JasonLG1979** [comment]
This can be closed. It works fine with Pithos now.

**Comment by dkogias** [comment]
Yup, WFM (F24, Pithos from rpmfusion)
