### ISSUE TITLE
Slider disappears when pressing Next two times

### ISSUE THREAD

**Issue by archdria** [eonpatapon/gnome-shell-extensions-mediaplayer#218]
Steps to reproduce (regardless the indicator position):
1. Start playing a song
2. Click Next
3. Click Next
4. Slider is gone

Thanks in advance :)

**Comment by badcel** [comment]
This works for me. Which player are you using? Which slider exactly vanishes?

**Comment by archdria** [comment]
Oops, sorry for the lack of information.
I'm using Rhythmbox and the slider that is missing is the progress slider (not the volume).
I've realised soometimes it disappears the first time I click next, some other times I have to click several times...

I haven't managed to reproduce it with VLC, for instance...

**Comment by archdria** [comment]
Thank you! :)
