### ISSUE TITLE
Better support for internet radio

### ISSUE THREAD

**Issue by acabal** [eonpatapon/gnome-shell-extensions-mediaplayer#222]
Hi there, great extension, thanks!

I often listen to internet radio and there's two improvements to this extension that would make it spiffier:

1. Right now if an internet radio stream is playing, a "cd" icon is shown.  It would be nice if we could get the "radio" icon to show instead.

2. Internet radio has no concept of "pause", so only a "stop" button is necessary.  So right now if I'm playing internet radio through Rhythmbox, clicking the "pause" button in this extension just does nothing.  Hiding the pause button in this case would be an improvement.

Re. the icon, I don't think mpris has a metadata standard for denoting an internet radio stream.  But a possible workaround would be:

    IF no cover art AND genre contains "radio" THEN
        cover = "radio"

Obviously that's not as good as having dedicated metadata, but it's a possible hack.

I can implement this and create a pull request this if it's something you'd like to add!

**Comment by eonpatapon** [comment]
Why not for the radio icon.

For the pause button you can open a bug in rhythmbox. The player should advertize that it can't pause the current stream by updating its CanPause property to False. You can check this property with d-feet for example.

**Comment by eonpatapon** [comment]
Fixed by #223
