### ISSUE TITLE
Position slider dissapears after pressing Next while listening music

### ISSUE THREAD

**Issue by gpoo** [eonpatapon/gnome-shell-extensions-mediaplayer#224]
When the music is playing and I press "next" to skip to the next song, the position slider dissapears.

I tried adding the volume slider, the playlist... but the problem only happens with the position slider. The only way to get it back is disabling the position slider and enable it back using the twrak tool, or re-starting Rythmbox.

**Comment by eonpatapon** [comment]
Are you using the git version ?

**Comment by eonpatapon** [comment]
See #218

**Comment by gpoo** [comment]
Indeed, it is a duplicate of #218  and it is fixed in master.

Thanks!
