### ISSUE TITLE
When a art cover does not exists, the extension shows the previous song's one

### ISSUE THREAD

**Issue by gpoo** [eonpatapon/gnome-shell-extensions-mediaplayer#226]
I have some tracks without art cover.  If the art cover exists for a song, the extension shows it correctly. However, if the next song does not contain art cover, the extension keeps showing the previous one, which has nothing to do with the song.

The expected behavior is to how a stub image, or empty space.

Maybe this is issue is related to #212

**Comment by gpoo** [comment]
I forgot to mention, I am using `git master` from a week ago and Rhythmbox.

**Comment by eonpatapon** [comment]
Can you try this branch ? Untested code though...

**Comment by gpoo** [comment]
Kind of.

Now there are songs with cover whose covers are not shown. It seems to work in some cases.

**Comment by gpoo** [comment]
FWIW, Rhythmbox shows the cover and some of them I remember the cover was shown in the extension as well.

**Comment by gpoo** [comment]
The fix produces a regression. It does not show any cover art now.
