### ISSUE TITLE
integration with gnome 3.18

### ISSUE THREAD

**Issue by DolphinStKom** [eonpatapon/gnome-shell-extensions-mediaplayer#229]
Hi! There are obvious problems with compatibility for the gnome 3.18.
on a home PC, extension start causing oops in gnome when he became 3.18 and crashes system...
it works on a laptop, but display problems for the player MPD and audacious (icon does not change, does not change the group name or song, you can not scroll through the track)
if I can say more details to solve the problem - tell me

**Comment by badcel** [comment]
Are there any messages in your system log? Did you try to remove and reinstall the extension (it lives in ~/.local/share/gnome-shell/extensions/mediaplayer@patapon.info)? Did you try another player on your laptop (e.g. VLC / Rhythembox)?

**Comment by DolphinStKom** [comment]
I didn't find anything in the logs... maybe I was looking for is not there, I will try more. 
I use Gentoo and has written for gnome-shell-extensions-mediaplaer ebuild [used git version] which is available to all in official layman overlay stuff (http://gpo.zugaina.org/gnome-extra/gnome-shell-extensions-mediaplayer). The extantion installed in /usr/share/gnome-shell/extensions/mediaplayer@patapon.info. I was trying to run audacious... and with it there is a problem, too.

**Comment by badcel** [comment]
You could try to install the extension from: https://extensions.gnome.org/extension/55/media-player-indicator/ instead of the ebuild,  to eliminate packaging problems.

**Comment by DolphinStKom** [comment]
I can't. My browser (Chromium) does not support installing Gnome Shell extensions from this website... so I decided to write the ebuild for the system, the installation proceeds normally, and the extension to work before normal

**Comment by DolphinStKom** [comment]
I have been installed Firefox and extension through it... but it did not help.
and I can control as before, but the mapping of the cover and track information is not correct

**Comment by badcel** [comment]
Did it install on your regular pc via the website?

The display problems are probably not related to an installation issue on your laptop but s.th. else.

**Comment by bmbaker** [comment]
I'm having the same problem, i just updated from the github repository and now gmusic guayadeque all crash gnome-shell with dreaded "oop" i think it has something todo with
"Arch news item: https://www.archlinux.org/news/c-abi-change/
wxWidgets-3.0, gstreamer and others are rebuilt as part of abi change
Script given in news item will flag this package.
Force a rebuild of this package.
Guayadeque does not install libstdc++ but is linked against it via wxWidgets."

cheers

**Comment by bmbaker** [comment]
this is from journalctl from arch setup
"gnome-session[1203]: (gnome-shell-extension-prefs:4333): GLib-GIO-ERROR **: Settings schema 'org.gnome.shell.extensions.mediaplayer' does not contain a key named 'status-size'

gnome-session[1203]: (gnome-shell:1276): GLib-GIO-ERROR **: Settings schema 'org.gnome.shell.extensions.mediaplayer' does not contain a key named 'trackbox-template'

Jan 05 20:59:56 dream-on gnome-session[1203]: gnome-session-binary[1203]: WARNING: Application 'gnome-shell.desktop' killed by signal 5

**Comment by eonpatapon** [comment]
Seems the gschema is not up-to-date

**Comment by bmbaker** [comment]
Is there a way to update the gschema?

**Comment by eonpatapon** [comment]
how do you install the extension ?

**Comment by bmbaker** [comment]
Direct from git

**Comment by bmbaker** [comment]
Interesting i just downloaded the zip from here and re-installed everything, and now it totally works!!
