### ISSUE TITLE
Change label from "Volume" to "Media Volume"

### ISSUE THREAD

**Issue by amig** [eonpatapon/gnome-shell-extensions-mediaplayer#23]
I found the button writing confusing at first glance and suggest to change the label of the volume widget from "Volume" to "Media Volume".

Also, it would be nice to have the media name and icon open the application (like it does in Ubuntu).

One more thing, I think a "Mute" button is nice addition.

**Comment by InfernoZeus** [comment]
> Clicking on the left side of the slider or the volume label will mute the player

Sorry to dig up this old issue, but is that still the case? It doesn't work for me.
