### ISSUE TITLE
Start with indicators hidden in PanelIndicator when the 'run default player' setting is false

### ISSUE THREAD

**Issue by isacdaavid** [eonpatapon/gnome-shell-extensions-mediaplayer#230]
There should be no indicators in the panel when no media player is open, unless the indicator is used to start the media player.

_commonOnActivePlayerRemove() hides all indicators as expected, but the extension starts with the main indicator shown (at least for Panel.PanelIndicator) so one has to open and close a media player to make it disappear.

The fix is a trivial 'if' clause but I'm unsure whether it should go in the class init() method or after making the instance in extension.js; so I rather opened a ticket.

**Comment by JasonLG1979** [comment]
Works as you describe with current git.
