### ISSUE TITLE
Cover art is sometimes showing and sometimes not altought  all songs have cover art embeded.

### ISSUE THREAD

**Issue by mrlee14** [eonpatapon/gnome-shell-extensions-mediaplayer#237]
I use the latest version from git. I see similar or the same issue is already  reported by others.
gnome-shell  3.16.4
music-player: gmusicbrowser 1.1.15.2

It does also: When a art cover does not exists, the extension shows the previous song's one #226

**Comment by careca1970** [comment]
Hi there!
Same (or similar) bahaviour here. Starts normally, but then stops showing coverarts, volume, rating, etc. Can still control "Stop/start/back/forward", still shows playlists.
Installed extension from Gnome-extensions Webpage.
I am on Feddora 22 (Gnome 3.16). Rythmbox 3.2.1 with "CoverArt Browser 2.1.1" plugin.
Is there a way to debug the issue. Please, tell if we can give more input here!

**Comment by knuthingmuch** [comment]
I can confirm this on Shell 3.18.5 on Ubuntu.

**Comment by JasonLG1979** [comment]
@mrlee14 is this still an issue with the current git?

**Comment by mrlee14** [comment]
Hi there.  
I have:  gnome-shell-3.16  and  gmusicbrowser v1.1.15.2
This  time I get completely empty black frame 
![screenshot from 2017-01-29 02-51-01](https://cloud.githubusercontent.com/assets/16404565/22399926/e0897b7e-e5cd-11e6-8e40-0209402afa69.png)
whenever I play file containing cover art. If file played has no cover art embedded then i get just the icon of huge silver CD in the place.
The same/similar behavior. I don't know whether this happening with other music players. But it does with gmusicbrowser...

**Comment by JasonLG1979** [comment]
Is that with the latest git?

**Comment by JasonLG1979** [comment]
That looks like they are sending a malformed file url.

**Comment by JasonLG1979** [comment]
Do you get any logging messages from gmusicbrowser?

**Comment by mrlee14** [comment]
I have the latest extension from git. I will check what I get by gmusicbrowser....

**Comment by JasonLG1979** [comment]
I'm going to add logic to the extension that tests to make sure that the file actually exists. Right now we don't check and we just try to use whatever random string is provided. That should make it so that if the uri is malformed you'll get the default icon.

**Comment by mrlee14** [comment]
I tried to play one music file containing embedded cover art  with VLC and extension works normally it shows album art properly. It seems this is just gmusicbrowser issue... Do you have perhaps some suggestion which code section/function I have to check for errors/corrections/inclusions? I can perhaps do the working patch for gmb..

**Comment by JasonLG1979** [comment]
I would start here:
https://github.com/squentin/gmusicbrowser/blob/master/plugins/mpris2.pm#L316-L328

**Comment by mrlee14** [comment]
Good. I will check what can be fixed here (unless someone gets faster) ... actually I'm quite addicted to gmb music player (weird  chemistry is this) and would be nice this is fixed...

**Comment by JasonLG1979** [comment]
Basically the uri should be an absolute path like file:///home/jason/someimage.jpg for local files and something like this for remote images https://i.stack.imgur.com/AJxan.jpg. But really players should NOT send remote images to MPRIS they should locally cache the images themselves and send a file uri.

**Comment by JasonLG1979** [comment]
Basically if you can't open the image uri in a web browser it's malformed.

**Comment by JasonLG1979** [comment]
If there is no cover it is preferable to just not include "mpris:artUrl" in the metadata at all.

**Comment by mrlee14** [comment]
I tracking your suggestions... maybe you could do this patch your self if you have some time Perl is not so much difficult..... I try it....   :)  I'm not very handy with perl but all languages are similar....

**Comment by JasonLG1979** [comment]
I may but it's not high on my priority list. I'm still learning js,lol!!! Python is my primary language.

**Comment by mrlee14** [comment]
Js is cool and py is also great... Its all soo similar.... Im ever learning anything also my memory is gone unless regularly practice languages....now I need to remember a little from last perl attempts...

**Comment by JasonLG1979** [comment]
@mrlee14 I added logic to make sure the cover file actually exists before we try to use it. That should catch malformed uri's and show the default icons in that case.

**Comment by JasonLG1979** [comment]
You want to do me a favor and test this out:
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/tree/ui-redesign

It includes A LOT of changes and improvements(IMHO)

**Comment by JasonLG1979** [comment]
I installed gmusicbrowser, even with my PR it's hit or miss. Sometimes I get cover art sometimes I don't. (but I always get at least the default icons) The comments in the code say that it only supports embedded images my guess would be that it will only show a cover if the meta tag for the audio file has an embedded image? Have you tried to use a tag editor to make sure all your music has cover art embedded in it?

**Comment by mrlee14** [comment]
I trying ui-redesign branch and it shows default cd icon on the center. At least not showing empty art frame. It is OK.

**Comment by JasonLG1979** [comment]
I amended that PR a little bit ago. I'd re-download and install it. I found a couple a bugs I introduced.

**Comment by JasonLG1979** [comment]
I'm not sure how perl works in regards to file access but it looks like they're trying to extract the embedded image and save it to a cache file on the fly. They'd do better to have a separate cover art cache.

**Comment by JasonLG1979** [comment]
Yep, they're trying to give MPRIS an invalid/mangled/malformed uri. This is an example of what I get from gmusicbroswer.
```file:///run/media/jason/Backups/Music/7%20Horns%207%20Eyes/7%20Horns%207%20Eyes/01%02Yet%02You%02Still%02Choke.mp3%3Aalbum```

It looks like they're trying to feed mpris the image tag?

**Comment by JasonLG1979** [comment]
closed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/300
