### ISSUE TITLE
Expanding cover art breaks text

### ISSUE THREAD

**Issue by julianrichen** [eonpatapon/gnome-shell-extensions-mediaplayer#238]
If you click the cover art of the currently playing song it expands to ~80% the width of the panel and breaks the text.

![](http://i.imgur.com/owBOztE.png)

It might be better to expand the cover art to 100% and hide the text, or move the text below the cover art.

Distro: Debian Sid
Gnome: 3.18
Player: Lollypop

**Comment by JasonLG1979** [comment]
closed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/300
