### ISSUE TITLE
It doesn't work with Lollypop 0.9.85

### ISSUE THREAD

**Issue by simonbcn** [eonpatapon/gnome-shell-extensions-mediaplayer#243]
Arch Linux 64 bits
Gnome shell 3.18.3-3
Lollypop 0.9.85
gnome-shell-extensions-mediaplayer installed from https://extensions.gnome.org/extension/55/media-player-indicator/

My config (sorry it's in Spanish):
![media player indicator_002](https://cloud.githubusercontent.com/assets/428231/13002781/8ae932e8-d171-11e5-99d5-e98165943f65.png)

The extension only shows this when Lollypop plays:
![menu_001](https://cloud.githubusercontent.com/assets/428231/13002800/a2ba2daa-d171-11e5-94b1-396743eedc16.png)

**Comment by JasonLG1979** [comment]
Works pretty good for me with the latest git of both the extension and Lollypop.
