### ISSUE TITLE
Support for Musique audio player

### ISSUE THREAD

**Issue by artemjackson** [eonpatapon/gnome-shell-extensions-mediaplayer#245]
Is it possible to add support of [Musique](http://flavio.tordini.org/musique) audio player?

**Comment by JasonLG1979** [comment]
You have it a bit backwards. gnome-shell-extensions-mediaplayer is a MPRIS2 client(if that's the right word?). Musique would have to add MPRIS2 support.  If Musique were to add MPRIS2 support it would work with gnome-shell-extensions-mediaplayer and many other MPRIS2 clients/widgets/panel applets.

https://specifications.freedesktop.org/mpris-spec/latest/
