### ISSUE TITLE
Position slider only shows if the "Show the media player position slider" setting is toggled after start up.

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#246]
I'm in the  process of cleaning up/rewriting the MPRIS implementation in Pithos and as the title says to get the position slider to show up I have to toggle the setting once after  Pithos starts up. After that it works fine until I quit Pithos. The rewrite is roughly based on GNOME Music's Implementation and as far as I can tell follows spec?  

My "MPRIS_changes" branch with the relevant code:
https://github.com/JasonLG1979/pithos/tree/MPRIS_changes

This applet works as expected in Cinnamon.
https://github.com/Koutch/Cinnamon-sound-with-apps-volume

The default Cinnamon sound applet also does not show the song progress. Although it lacks the ability to toggle it on and off. I'm not sure if that has anything to do with it.

**Comment by JasonLG1979** [comment]
Update:
After looking through the source the extension it seems that if the "CanSeek" prop is False the position slider is hidden even if a valid "Position" prop is given and "mpris:length" is provided. I managed to get it to work by lying and setting "CanSeek" to True.

IMHO "CanSeek" should not be used to determine if the position slider is shown.

Here's what I've done to get full functionality:
https://github.com/JasonLG1979/pithos/tree/MPRIS_fixes

**Comment by eonpatapon** [comment]
You are right, CanSeek == False shouldn't hide the slider but only disable it

**Comment by JasonLG1979** [comment]
Disabling it would be the same as hiding it wouldn't it pretty much? My question is why disable the slider on CanSeek == False? Just because a player can't seek doesn't mean it can't provide position and duration information. The slider IMHO should depend on the "Position" prop and "mpris:length" metadata. If valid values are given for both of those the slider should not be disabled.

**Comment by eonpatapon** [comment]
By disable I mean keep it visible but don't allow to interact with it

**Comment by JasonLG1979** [comment]
On the master branch unless the CanSeek prop is True it is not shown even if it is enabled in the setting.

**Comment by JasonLG1979** [comment]
#288 is a step towards fixing this.

**Comment by JasonLG1979** [comment]
@eonpatapon the CanSeek prop is still basically a toggle to hide and show the slider. If you could point me in the right direction to making it non-interactive instead of hiding it. I'm guessing you can toggle sensitivity but that usually grays out stuff. I'd like for it to look normal just not respond to interaction if the CanSeek prop is false.

**Comment by eonpatapon** [comment]
@JasonLG1979 in this case you probably want to bypass this.player.seek line 171 in src/ui.js

**Comment by JasonLG1979** [comment]
Right on thanks!!! When you merge/close the PR's I have open I'll start work on this.
