### ISSUE TITLE
Error checking http cover urls.

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#248]
I could be wrong but it seems that no error checking is done in the process of downloading and saving covers to a temp file. From what I understand from the code an attempt is made to download the cover but if it were to fail the existing/previous cover is reused for the next song. If the download fails something like the generic audio mime type icon should be used for the cover art.

``` 
      if (state.trackCoverUrl !== null && state.trackCoverUrl !== this.state.trackCoverUrl) {
        if (state.trackCoverUrl) {
          let cover_path = "";
          // Distant cover
          if (state.trackCoverUrl.match(/^http/)) {
            // Copy the cover to a tmp local file
            let cover = Gio.file_new_for_uri(decodeURIComponent(state.trackCoverUrl));
            // Don't create multiple tmp files
            if (!this._trackCoverFileTmp)
              this._trackCoverFileTmp = Gio.file_new_tmp('XXXXXX.mediaplayer-cover')[0];
            // asynchronous copy
            cover.read_async(null, null, Lang.bind(this, this._onReadCover));
          }
          // Local cover
          else if (state.trackCoverUrl.match(/^file/)) {
            state.trackCoverPath = decodeURIComponent(state.trackCoverUrl.substr(7));
          }
        }
        else {
          state.trackCoverPath = '';
```

**Comment by eonpatapon** [comment]
This code has been removed in favor of using Gio.File.new_for_uri directly into a Gio.FileIcon (see ui.js)

**Comment by JasonLG1979** [comment]
Slightly different code now, but it still looks like you're not checking for errors? file could potentially be None(or the equivalent in your bindings)
```
        else if (state.trackCoverUrl) {
          let file = Gio.File.new_for_uri(state.trackCoverUrl);
          let gicon = new Gio.FileIcon({file: file});
          let coverIcon = new St.Icon({gicon: gicon, style_class: "track-cover",
                                       icon_size: this.trackCover.child.icon_size});
          this.trackCover.child = coverIcon;
```

In python the check would look something like this:
###pseudo code###
```
elif state.trackCoverUrl:
    file = Gio.File.new_for_uri(state.trackCoverUrl)
    gicon = Gio.FileIcon.new(file)
    if gicon is not None:
       #use the gicon as our icon
  else:
    #deal with the fact that there was an error trying to use the given url as the cover
```

**Comment by eonpatapon** [comment]
Yes state.trackCoverUrl can be an empty string in this case an icon is displayed

**Comment by JasonLG1979** [comment]
Is null the same as an empty string?

**Comment by eonpatapon** [comment]
Well null and "" == false, so if will not be executed.

As for the wrong uri I'm not sure how Gio.File handles it. Anyway it's the way it's done in the gnome-shell mpris implementation

**Comment by JasonLG1979** [comment]
> Anyway it's the way it's done in the gnome-shell mpris implementation

That doesn't mean it right. You can pass whatever wack a do string you want to Gio.File it's just a wrapper. You won't find out it's not valid until you check.

**Comment by JasonLG1979** [comment]
What I mean is if you pass an invalid url to Gio.File you won't know it's invalid unless you check to see if gicon is null or None or whatever.

**Comment by eonpatapon** [comment]
Sure I agree it can be improved

**Comment by JasonLG1979** [comment]
All you have to do is:

```
if gicon:
   #use gicon
else:
    #use default cover
```

**Comment by JasonLG1979** [comment]
> As for the wrong uri I'm not sure how Gio.File handles it.

To clarify: 

Gio.File doesn't handle invalid uri's. Except for maybe checking to see if the uri "looks" like a valid uri. 

You can't know if the uri is actually valid until you try to use it.

new Gio.FileIcon({file: file}) returns Gio.Icon or null on error. 

The error could be caused by many different reasons. For example the uri "looks" valid but is in fact absolute gibberish. Or one of many other things that can go wrong when you try to fetch an image in any other way.

In the event of an error you're actually calling:

```javascript
          let coverIcon = new St.Icon({gicon: null, style_class: "track-cover",
                                       icon_size: this.trackCover.child.icon_size});
```

I'm not sure what that actually does but I'm guessing you'd rather not blindly hook Gio.File and  new Gio.FileIcon together without some kind of error checking?
