### ISSUE TITLE
Provide option to disable scrolling from changing track

### ISSUE THREAD

**Issue by jwarkentin** [eonpatapon/gnome-shell-extensions-mediaplayer#253]
This happens to me all the time. I accidentally bump my mouse over the media player indicator as I'm scrolling and it starts changing the track forward or backward (always when using the touchpad). I already have keyboard shortcuts setup for changing the track when I want and changing the track with the scroll wheel has never been intentional. It would be awesome if there was a setting to disable that functionality.

**Comment by JasonLG1979** [comment]
Added this to https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/300

**Comment by JasonLG1979** [comment]
closed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/300
