### ISSUE TITLE
Layout issues with another extension

### ISSUE THREAD

**Issue by sojusnik** [eonpatapon/gnome-shell-extensions-mediaplayer#258]
The placement of the mediaplayer extension is somehow buggy, when the [shutdown timer](https://github.com/neumann89/ShutdownTimer) extension (on Gnome's [extensions site](https://extensions.gnome.org/extension/792/shutdowntimer/)) is installed, as you can see [here](http://i.imgur.com/ORpb4zC.png) (shutdown extension enabled) and [here](http://i.imgur.com/vRm1JDq.png) (shutdown extension disabled). According to the maintainer of the shutdown extension, this should be easily fixed by adopting some lines in the mediaplayer extension, as explained [here](https://github.com/neumann89/ShutdownTimer/issues/22#issuecomment-208249158).

**Comment by JasonLG1979** [comment]
I'm Googling my brains out trying to find a better way to intelligently and automatically put the extension in optimal place. I can't find any way to say "Hey put it between these 2 menu items." Everything seems to be referenced by index?(The docs really suck for Shell extension creation) as of right now the best I can do is set a sane default and add a user setting so you can put it where you want it.

**Comment by maweki** [comment]
I'm kinda working with the design team on a best practices guide to do this. But this won't be for the next cycle.

**Comment by JasonLG1979** [comment]
It would be helpful if they named the items. someItem.actor.get_name() always returns nulll I maybe doing something wrong. I'd love to be able to iterate over the menu and say basically if someItem.actor.get_name() == "whatever" do this.

**Comment by maweki** [comment]
so there is a get_name-method? Okay. I am looking into that. If this is easy enough, I should get the shell team to use names on the items (or do it myself).

**Comment by maweki** [comment]
you could use `Main.panel.statusArea.aggregateMenu.menu._getMenuItems()` and check at least for the types of the items. Then you will find "legitimate" entries and seperators. So you could, for example, add the controls as the last item before the first seperator or the first item after the last one etc.

**Comment by JasonLG1979** [comment]
I know. I played with that but it only tells me the Class and that's of limited use. The "Classes" are just built out of St widgets most of the time a St.Box. The main widget in the class is the "actor" St widgets are just wrappers around Clutter actors. You can name a clutter actor or for that matter just set a name var in the class.

**Comment by JasonLG1979** [comment]
That way you could just do:
Main.panel.statusArea.aggregateMenu.menu._getMenuItems()[i].name

**Comment by maweki** [comment]
But they do seem to set some GObject property (https://github.com/GNOME/gnome-shell/blob/master/js/ui/status/volume.js#L156-L163). Maybe there's a way to access that.

**Comment by JasonLG1979** [comment]
That looks more like args for the "Class" constructor. I don't think those are GObject props. I don't think they would be very useful as they represent individual elements in the volume menu item. I wouldn't count on the names staying the same. I would treat them as an implantation detail.

**Comment by JasonLG1979** [comment]
*implementation detail

**Comment by JasonLG1979** [comment]
I'm talking more like an API. Like here is stable way to identify the item as a whole. Snooping around in the widget elements' Class constructors to tell what the item is a bad idea IMHO.

**Comment by maweki** [comment]
> Snooping around in the widget elements' Class constructors to tell what the item is a bad idea 

Of course it is and I outlined some issues (including the positioning) quite some time ago (https://wiki.gnome.org/Projects/GnomeShell/Extensions/Future) but I can't seem to get any traction in the core developer community or design teams to do anything about it. :(

**Comment by JasonLG1979** [comment]
That's why IMHO letting the user decide where to put it is the best option ATM.

**Comment by JasonLG1979** [comment]
Tested with Ubuntu 16.04 with GNOME version 3.18 (VM) and Fedora 25 with GNOME version 3.22.(bare metal) A default position of 6th from the top puts extension just above the user menu item. Ofc other extensions can affect that depending on where they place themselves. But again the user can always put it where ever they want.

Here's a screenshot from Ubuntu 16.04 GNOME:
![screenshot from 2016-12-13 18-31-03](https://cloud.githubusercontent.com/assets/6667703/21165187/7ce3e692-c163-11e6-99f6-8d0ad990ed13.png)

**Comment by JasonLG1979** [comment]
> but I can't seem to get any traction in the core developer community or design teams to do anything about it. :(

They'll prob tell you to write an extension to set the ordering of the other extensions,lol!!!

**Comment by JasonLG1979** [comment]
closed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/300
