### ISSUE TITLE
Cover doesn't update with Spotify

### ISSUE THREAD

**Issue by qmarlats** [eonpatapon/gnome-shell-extensions-mediaplayer#260]
When using Spotify (I don't know with other players), the cover of the song is not updated. It works for the first song, then the cover doesn't change when the music changes; it changes some minutes later.
There is an other strange bug: when we use cover and not icon for indicator, there is one image that appear for the indicator, when I hover it with the mouse the image change, when I click the cover still the same but when I click on it there is again an other image. So there are 3 cover thumnails.

**Comment by SuperPichu** [comment]
I have a similar issue using Google Music Electron.

**Comment by mank319** [comment]
I encountered the same problem on Ubuntu 16.04 (Gnome `3.18.4`) and Spotify version `1.0.28.89.gf959d4ce`. I figured out that you can force an update when changing the position of the indicator (e.g. from right to center) although that sometimes that leads to the default placeholder album cover.

**Comment by qmarlats** [comment]
The bug not only happen with this extension in fact, it happens in Gnome notifications too (Gnome 3.20.1). I will take a look on the Gnome bug tracker and create an issue if no one already exists.

**Comment by eonpatapon** [comment]
Seems to me that the application isn't properly sending updates. Please check with other players.

**Comment by tomvanderlee** [comment]
I am writing my own app with mpris2 integration and I notice this issue too. I definitely send updates every time the song changes, but the cover wont update.

**Comment by eonpatapon** [comment]
Do you send always the same path for the cover ?

**Comment by tomvanderlee** [comment]
@eonpatapon Nope, urls  are different.

If I start the app it loads the image of the first track. Then when I switch the track (with a different cover url), I see the old cover fade out (like it is about to reload), but then it comes back instead of the new one.

**Comment by jooon** [comment]
I see this as well with Ubuntu 16.04. I am sure it worked one time, not sure when. I work at Spotify and have tried to fix MPRIS support in the linux client in the Spotify 1.0.x code base. The only thing I can think of now, where Spotify is misbehaving that might trigger this problem is that it sends 4 identical PropertiesChanged for Metadata at the same time when switching tracks and the artUrl is an https url which then redirects to a http url.

I want to fix that and eventually just give a file path in artUrl (so offline and local files playback works better).

**Comment by icasdri** [comment]
The issue of covers not updating may be related to #271

**Comment by eonpatapon** [comment]
This commit should fix issues with spotify. I've been using the 1.0.36 version.

Hope it will work for you

**Comment by tomvanderlee** [comment]
@eonpatapon Can confirm. It works!
