### ISSUE TITLE
missing trackDate metadata

### ISSUE THREAD

**Issue by roizcorp** [eonpatapon/gnome-shell-extensions-mediaplayer#261]
I would like to add the Date metadata, as far as I looked, I was not been able to identify any support for it

**Comment by eonpatapon** [comment]
Don't seem to be available via MPRIS see: https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index12h4

There is contentCreated and lastUsed but I believe it's not what you are looking for ?

**Comment by roizcorp** [comment]
Thanks,
Not really, I wanted a date for add the year of an album (in case the track is part of an album)

It's really odd that they have "composer" and not date which is more basic metadata

Thanks though

**Comment by roizcorp** [comment]
I tried contentCreated? does not seems it is what I'm looking for
