### ISSUE TITLE
Incompatible with GNOME 3.20

### ISSUE THREAD

**Issue by pizzamaker** [eonpatapon/gnome-shell-extensions-mediaplayer#262]
As of now, this extension is not working under 3.20.

**Comment by Dumbledorf** [comment]
I can confirm this. It needs a fix.

**Comment by Dumbledorf** [comment]
Any solution yet?

**Comment by eonpatapon** [comment]
Works fine here

**Comment by JLCCI** [comment]
Hmm with Fedora 24 I can only see Rhythmbox icon but cannot control anything. Any ideas?

**Comment by JasonLG1979** [comment]
@JLCCI closing this as the latest git works fine for me in Fedora 25.
