### ISSUE TITLE
[Regression] Fix for #226 makes that no art cover is shown in gnome-shell 3.18

### ISSUE THREAD

**Issue by gpoo** [eonpatapon/gnome-shell-extensions-mediaplayer#263]
`git bisect` says that commit 8ed766 introduces the regression.

**Comment by eonpatapon** [comment]
Which player do you use ?

**Comment by gpoo** [comment]
Rythmbox

**Comment by JasonLG1979** [comment]
@eonpatapon 
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/a5d8e3bd4cdf1df71d10ba86117a7bafe3031cab

Fixed this.

**Comment by gpoo** [comment]
It seems to work fine. Thanks!
