### ISSUE TITLE
Want to search current playlist

### ISSUE THREAD

**Issue by roizcorp** [eonpatapon/gnome-shell-extensions-mediaplayer#264]
I would like to have a "while you type" search text field and beneath a results section

This will allow me total control over my remote MPD player without any other MPD client. 
Search should match title, album and artist
Results should have at least 3 columns title, artist and title

I can create mockups if needed

**Comment by JasonLG1979** [comment]
The extension would need to add support for the TrackList interface to be able to search individual tracks.

https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html

Even then it's up to the player to provide the TrackList and the spec clearly says that it's not intended to show or give access to the contents of an entire playlists. It's intended to be a more narrow slice of a few recently played tracks and upcoming tracks to show context. It's not even guaranteed that previous tracks in the Tracklist are even from the current playlist.

**Comment by JasonLG1979** [comment]
Closing this.

Even if we to add Tracklist support, your feature request goes against the intent/purpose of the TrackList interface to quote the spec:

"Note that the (memory and processing) burden of implementing the TrackList interface and maintaining unique track ids for the playlist can be mitigated by only exposing a subset of the playlist when it is very long (the 20 or so tracks around the currently playing track, for example). This is a recommended practice as the tracklist interface is not designed to enable browsing through a large list of tracks, but rather to provide clients with context about the currently playing track."
