### ISSUE TITLE
Media information closing when changing track with VLC

### ISSUE THREAD

**Issue by p02030507111317** [eonpatapon/gnome-shell-extensions-mediaplayer#265]
I have a problem when i change track, the informations disappear until i switch again or i pause the track (the buttons << || > >> and the bars remains).
This problem appears on Debian 8 with gnome-shell 3.14.4

**Comment by eonpatapon** [comment]
Please test with the latest master branch.

It should be fixed

**Comment by clavierp** [comment]
It works perfectly. Thank you.

**Comment by p02030507111317** [comment]
It works perfectly. Thank you for this great extension.
