### ISSUE TITLE
Doesn't start on startup

### ISSUE THREAD

**Issue by wamoyo** [eonpatapon/gnome-shell-extensions-mediaplayer#266]
I have to visit the gnome extensions site and turn it on every time I restart the machine. Gnome Ubuntu 14.04.

**Comment by wamoyo** [comment]
Any ideas?

**Comment by wamoyo** [comment]
Hmm.... wonder if there's a workaround.

**Comment by JasonLG1979** [comment]
Issues with Ubuntu 14.04 will likely never get fixed. 3.10 is over 3 years old. I don't know about the other devs but I don't plan on supporting any GNOME Shell versions older than what came with the latest LTS. Currently that's 3.18.

@eonpatapon your thoughts on how far back we should go with support?

**Comment by eonpatapon** [comment]
yes I think 3.18 is old enough

**Comment by JasonLG1979** [comment]
Thanks.

**Comment by JasonLG1979** [comment]
My thought is that we drop support for old LTS's when the current LTS hits the xx.xx.1 update.
