### ISSUE TITLE
No schema is set for gsettings "org.gnome.shell.extensions.mediaplayer"

### ISSUE THREAD

**Issue by thomaskisler** [eonpatapon/gnome-shell-extensions-mediaplayer#268]
There is no schema set for the path org/gnome/shell/extensions/mediaplayer and therefore it is not possible to access the key/values of the application via the gsettings command.

I hope this is somehow understandable, I am new to the whole gsettings thing. As I understand if there would be "org.gnome.shell.extensions.mediaplayer" set (where now "No schema" is seen the screenshot), one could use gsettings. I would be glad to answer any further questions.

![screenshot-mediaplayer-extension-gnome-screenshot-no-schema](https://cloud.githubusercontent.com/assets/4718006/16036239/469fc6fa-321b-11e6-866e-de79f8c05e4d.png)

**Comment by eonpatapon** [comment]
You need to specify the schema dir. For example with gsettings you can run:

gsettings --schemadir .local/share/gnome-shell/extensions/mediaplayer@patapon.info/schemas/ get org.gnome.shell.extensions.mediaplayer rundefault

Didn't check if it's possible with d-conf.

Please note that you can modify the settings with the gnome-shell-extension-prefs tool
