### ISSUE TITLE
Possibility to disable notification on track change

### ISSUE THREAD

**Issue by thomaskisler** [eonpatapon/gnome-shell-extensions-mediaplayer#269]
It would be great, if it would be possible to add the functionality to disable the "notification on track change". I haven't found any way to disable this so far.

**Comment by badcel** [comment]
As far as I know the extension is not showing any system notifications. Can you explain in more detail which player you are using and what you are experiencing?

A guess would be, that your music player is displaying the notifications by itself. So checking the properties / plugins of your music player would be an option.

**Comment by eonpatapon** [comment]
Yes the extension isn't sending any notifications, closing this.
