### ISSUE TITLE
Cover art not updating with mpDris2/python-mutagen/python2-mutagen. Gnome 3.20. Arch Linux.

### ISSUE THREAD

**Issue by PrMinisterGR** [eonpatapon/gnome-shell-extensions-mediaplayer#271]
When mpd starts, the cover displays properly. When tracks change, the extension only shows an empty disc, even for tracks that belong in the same album. Gnome's indicator itself shows the correct cover (which means that mpDris2/mutagen send it). It will also display in the extension if I restart the shell on the fly.

**Comment by icasdri** [comment]
I have also run into a similar issue, although intermittently, with Pithos. The cover art would refuse to change (getting stuck on a previous cover art instead of just showing a blank disc) unless either Pithos or Gnome Shell is restarted.

**Comment by miguelcarax** [comment]
I have the same issue, same distro same gnome version.

**Comment by eonpatapon** [comment]
Can you test with this commit ? Thanks

**Comment by reb-lws** [comment]
I have the same issue as well. Tried the latest commit and it hasn't fixed the problem for me.
