### ISSUE TITLE
cmus support

### ISSUE THREAD

**Issue by miguelcarax** [eonpatapon/gnome-shell-extensions-mediaplayer#273]
It will be possible a [cmus](https://cmus.github.io/) support? Thanks!

**Comment by icasdri** [comment]
I believe this would entail *cmus* implementing the MPRIS2 protocol specification, and not anything on the part of the mediaplayer extension developers.

**Comment by eonpatapon** [comment]
Exactly, MPRIS must be implemented in cmus to be able to use this extension with cmus
