### ISSUE TITLE
Raise should prefer to call the Raise method supplied by the player

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#284]
Raise should prefer to call the Raise method supplied by the player, not activate_full.
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/player.js#L336-L341

Reasoning:

The CanRaise prop is(or at least should be) set true or false by the player to indicate if the player can be raised. In the case of a player with no UI that may not be possible. (I don't know what happens if you try to activate/raise a player with no UI?)

In the case that the prop is set to true the extension should call the player supplied Raise Method. It's there for that exact purpose. Players may want to to other things in addition to raising the player. In Pithos for example we keep track of window position, calling activate_full breaks that functionality. 

Simply reversing the if seems reasonable:

```js

     raise: function() {
      if (this.info.canRaise)
        this._mediaServer.RaiseRemote();
      else if (this.info.app)
        this.info.app.activate_full(-1, 0);
    },
```

**Comment by eonpatapon** [comment]
Done that a long time ago so I don't remember exactly why it was done that way but I think when calling raise some players didn't show their window on the current workspace hence the activate_full.

I'm not against chaging this, but tests must be made with a bunch of players.

**Comment by JasonLG1979** [comment]
They should be calling present or present_with_timestamp or something similar. I do believe that activate_all calls present. I'll just have to override present and put the positioning logic there. To me though it's up the app to decide what they want to do right or wrong it's on them.

**Comment by JasonLG1979** [comment]
I think the solution is to add this to the known bugs/workarounds so people know that raising with the extension may not be actually calling the Raise Method on the interface.
