### ISSUE TITLE
Define a "Ratings" interface.

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#294]
The extension supports changing ratings in a few apps by adding app specific code. It would be much easier and cleaner for us to define a Ratings interface and then when an app wants to be able set ratings all they would have to do is follow the spec of that new interface.

The current system is bad because:

1. You're maintaining someone else's code.
2.  It's inefficient. New code has to be written for each player that wants to be supported.

The interface could be  org.mpris.MediaPlayer2.ExtensionRatings 

The "Extension" prefix is because it's an extension of the standard Mpris interfaces.

**Comment by JasonLG1979** [comment]
It won't need to be very complicated.

Methods:

RateTrack(o: TrackId, d: Rating)
Rate a track on a scale of 0.0 to 5.0

UnRateTrack(o: TrackId)
Clear a track rating.

Properties:

RatingIsBoolean(b) #optional assume ratings are not boolean if this prop does not exist.
Used to decide how to display the ratings. If the rating is boolean a single icon should be used to represent the rating. Players with boolean ratings will use 0.0 to represent "False" and 5.0 to represent "True" anywhere ratings are used.

TrackRatings(a{sv}) # optional for support in conjunction with the tracklist interface.
An array of TrackId's their rating and if they can be rated.
key value pairs.
{"trackId": *trackid obj path,
"rating": *rating double,
"canBeRated": *boolean}

CurrentTrackRating(o: TrackId, d: Rating, b: canBeRated)
The current track's obj path, rating and if it can be rated.

Signals:

RatingChanged(o: TrackId, d: Rating)
Emitted when a player has changed the rating of a track.

**Comment by JasonLG1979** [comment]
For this extensions purpose since it doesn't support the TrackList interface a player would need:
The RateTrack and UnRateTrack Methods. The CurrentTrackRating and optionally the RatingIsBoolean Properties. And the TrackRatingChanged signal. If they provide the Ratings interface with those they would get automatic support. No app specific code in your code base.

**Comment by eonpatapon** [comment]
I'm not sure this would be adopted unless it is added into the official MPRIS spec.

Maybe we could start a discussion about this in the mpris-spec ml and see if there is some interest ? But it seems quite dead...

https://www.freedesktop.org/wiki/Specifications/mpris-spec/

**Comment by JasonLG1979** [comment]
> I'm not sure this would be adopt

Well if you deprecated the old way of doing things if a player wanted to be able to set ratings they wouldn't have much choice would they?

> Maybe we could start a discussion about this in the mpris-spec ml and see if there is some interest ? But it seems quite dead...

It doesn't seem like it was every really even used that much. I'm not even sure you could ever say that it was ever alive,lol!!! I think I've read just about every message. But from what I understand it's perfectly OK to extend Mpris as long as you use a unique interface name. Amarok does it.

https://cgit.kde.org/amarok.git/tree/src/dbus/mpris2/MediaPlayer2AmarokExtensions.cpp?h=v2.8.90

**Comment by JasonLG1979** [comment]
To me makes much more sense to have a standard ratings extension then to have each app write their own ratings extension and write new code every time you want to support said custom ratings extension. That seems wasteful and redundant.

**Comment by JasonLG1979** [comment]
If you like I can start a github repo that hosts the ratings extension spec so it's separate from your project? That way they are not directly tied together and you wouldn't have to field questions/support it?

**Comment by JasonLG1979** [comment]
In D-Feet the interface would look like this:
![screenshot from 2016-11-25 10-33-06](https://cloud.githubusercontent.com/assets/6667703/20631125/ac9a4b32-b2fa-11e6-96ca-2a844e46dce7.png)

**Comment by TingPing** [comment]
I certainly agree we should *not* add interfaces to `org.mpris.MediaPlayer2` unless they are official.

Speaking just for Pithos, I honestly thing an app specific path seems reasonable, Radio clients are sort of a different use-case than the existing ratings and there aren't that many radio clients that expose their ratings externall, Pithos being one of the few.

**Comment by JasonLG1979** [comment]
https://lists.freedesktop.org/archives/mpris/2012q4/000054.html

"Yes, exposing extended functionality through additional interfaces on
the mpris player object is a completely valid use case IMO."

**Comment by JasonLG1979** [comment]
There's no difference between an an app specific path and a predefined more generic extension other than an extension would be documented and could be used by other players not just Pithos. Again to remove redundancy and duplication of effort. That's one of the points of OSS isn't it? So you don't have to reinvent the wheel over and over again?

**Comment by badcel** [comment]
I think it is a good idea to have a ratings interface. Probably it would be at least worth a try to present your ideas to the mpris mailing list. Perhaps there will be some feedback or discussion. It would be bad, if this extension has some custom rating interface and in 1 year someone else defines a different (but official) interface in the mpris spec.

If your idea gets into the spec all players are benefitting, because there are more mpris extensions, e.g. for kde which could than also implement this feature.

**Comment by JasonLG1979** [comment]
The idea has already been brought up in the mailing list, with not much interest. And even if they did like my idea as slow as the Mpris spec moves it would be YEARS before it made it in the spec.

**Comment by JasonLG1979** [comment]
I'll give it a shot though I guess?

**Comment by JasonLG1979** [comment]
I honestly think the Mpris spec is meant to be a base to be extended as needed that's why it's missing so much.

**Comment by badcel** [comment]
I'm not much into defining interfaces which are independent of distributions / toolkits. But I think the problem is that every developer wants to have a different interface and it is hard to define an interface which fits the needs of all interested developers / users.

If there is no response it would be possible to research if there is other software which has a rating interface and define an interface together, to create a standard which is not covered by the spec, but already adopted by more than one implementation.

Even if nobody is interested, perhaps you could be the author of the next version of the spec? How knows? :-)

**Comment by JasonLG1979** [comment]
Maybe?

**Comment by JasonLG1979** [comment]
@badcel I sent this to the mpris mailing list:

>I've got a question in regards to extending mpris2. The current spec has no way to set/change track ratings(or any other metadata for that matter) Will the ability to set ratings ever be added? If not is there any objection to someone creating a non-standard org.mpris.MediaPlayer2.ExtensionRatings interface to fill in the gap? Currently a few apps already have app specific ratings extension interfaces but in the interest of not reinventing the wheel I thought it might not be a bad idea to have one Extension that could be shared by apps to make developing mpris2 clients easier as setting ratings is pretty high up on the feature request list and ATM that requires adding app specific code for every app that wants support . The idea has been so far discussed here:
 
>"link to this issue"

>The input of the authors of the mpris spec would be greatly appreciated.

**Comment by fb87** [comment]
Would you please consider a differentiation between auto-generated and manual-set ratings? Lollypop for example generates auto ratings based on the listening behaviour, while they could be overwritten manually. The manual set ones are highlighted appropriately to the GTK theme, btw. Would be really great!
