### ISSUE TITLE
Not working - not visible - in Fedora25, Gnome 3.22

### ISSUE THREAD

**Issue by alan12345678** [eonpatapon/gnome-shell-extensions-mediaplayer#297]
Only got to love this extension a few weeks ago, now it's not even listed/available on the Gnome Extensions page (firefox 50) ;0(

Should this extension work in the above spec? Is my system borked? Or are you updating? Don't really want to start building locally if I can help it.

**Comment by JasonLG1979** [comment]
It's right here? https://extensions.gnome.org/extension/55/media-player-indicator/

**Comment by alan12345678** [comment]
Sorry, I don't think I was clear. I know where the web page is. What I mean is that if I use Gnome Tweak for example, and "get more extensions" and which then takes me to the above page, your extension is not visible using Fedora 25, Gnome 3.22, Firefox 50.0.2, UNLESS I click the option "compatible with/all versions" and THEN I can see your extension. However, once installed, it 'disappears' from under Gnome Tweak etc.

**Comment by JasonLG1979** [comment]
I can reproduce this, I'm also running Fedora 25. Looking in ```~/.local/share/gnome-shell/extensions``` it appears that the extension is never actually downloaded. I'm not sure how extensions are updated/synced with their upstream. If it's an automatic or manual process? But If I had to guess @eonpatapon just needs to update it at  https://extensions.gnome.org/. Until then installing from source is not hard and takes about 5mins.

**Comment by alan12345678** [comment]
@JasonLG1979  could you please just point out/link to the build you use which works with the above configuation? I read the notes here and the branches above, but couldn't see one that specifically seems to work with my configuration?

**Comment by JasonLG1979** [comment]
The main branch works just fine for me. I can attest from looking at and tweaking the internals of the extension that if it doesn't work with your particular player it's a bug on the players side.

**Comment by alan12345678** [comment]
It's not a matter of it not working with my player (Quodlibet) and which it did before, but that it doesn't install at all. So, unless it's updated (rather curious why not) I have to completely go without - which is now a pain.

**Comment by JasonLG1979** [comment]
Installing from source literally takes less than 5min.

**Comment by JasonLG1979** [comment]
> rather curious why not

I don't think the main dev uses GNOME anymore. From what I can tell it's basically in maintenance mode. I don't think it's a high priority.

**Comment by alan12345678** [comment]
Sorry, I must be being thick - from the above I can't actually see a link to the source code? Presumably there's a page with the git script too?

**Comment by JasonLG1979** [comment]
Link? The main branch is the default branch.

**Comment by alan12345678** [comment]
Yes, now I see sorry. Thanks for your help :0)

**Comment by JasonLG1979** [comment]
To install:

```sudo dnf install git automake gnome-common gettext glib2-devel```

```git clone https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer.git```

```cd gnome-shell-extensions-mediaplayer```

```./autogen.sh```

```make```

```sudo make install```

To uninstall cd to the folder:

```sudo make uninstall```

**Comment by eonpatapon** [comment]
Yes I have to upload it on e.g.o
