### ISSUE TITLE
UI design discussion

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#298]
I've been playing with some things to clean up the UI a bit. So far I've made some progress(despite the fact that the gjs & shell extension docs <b>SUCK!!!</b>) I've managed to tighten up the alignment of widgets and what not. Here's what I have so far:

![screenshot from 2016-12-11 01-43-30](https://cloud.githubusercontent.com/assets/6667703/21078904/03ca84d8-bf46-11e6-9216-3f3274f1137c.png)
![screenshot from 2016-12-11 01-43-34](https://cloud.githubusercontent.com/assets/6667703/21078905/03cbc92e-bf46-11e6-9649-f2a1a37c732f.png)
![screenshot from 2016-12-11 01-43-44](https://cloud.githubusercontent.com/assets/6667703/21078906/03ccaa42-bf46-11e6-9108-8f7bb5e5476f.png)
![screenshot from 2016-12-11 01-43-46](https://cloud.githubusercontent.com/assets/6667703/21078907/03cd262a-bf46-11e6-94e4-ca9500fca1bb.png)

Like I said I managed to get everything to line up by pretty much getting rid of most of the custom style classes and using existing styles so things like padding, margins, sizes and what not get set by the theme. And I've managed to get the "cover zoom" to work correctly. The small cover size is 48px the large cover size is determined by the theme indirectly (It's the width of the parent container).

Those parts are all good and well but there are a couple things I figured should be discussed before I put in a PR.

1. Do we really need the Stop Button? Many Mpris applets don't have a Stop Button, It throws the control button box alignment off on themes with narrow menus and Stop can mean different things depending on what mode the player is in.

2. The Volume and Position Sliders; The volume label is redundant next to a pretty universally understood volume icon. I get that it's probably there to provide visual balance because of the track time but I wonder if we even need the track time either? We have a slider. I kinda like the track time, I just wish I could find a better place to put it.

**Comment by eonpatapon** [comment]
Looks great.

1. I don't know, I always liked to have the stop button and I usually I used it more than the pause button. But that's just me, maybe people find it not useful.

2. Yep the volume text was there just for alignement. Maybe it is not so bad to remove the track time. I don't know for others but that wouldnt bother me. I don't really care to know how long exactly is the song. And without it I still can see the progression or seek the track.

**Comment by JasonLG1979** [comment]
> I don't know, I always liked to have the stop button and I usually I used it more than the pause button. But that's just me, maybe people find it not useful

I go the the other way myself. I basically never use stop.

> Yep the volume text was there just for alignement. Maybe it is not so bad to remove the track time. I don't know for others but that wouldnt bother me. I don't really care to know how long exactly is the song. And without it I still can see the progression or seek the track.

Neither of the 2 applets I've found that have a position slider show the time(the KDE and Cinnamon sound applet) Not having a volume label also helps because it's one less thing to translate. And from a alignment perspective you never really know how long the translated word for volume will be. It could be 27 chars in some language,lol!!!  And there goes your alignment.  

I'm in the process of testing it on various themes. So far it works on every theme I've tested on with the exception of https://github.com/horst3180/vertex-theme. That theme has a very narrow menu so you end up with this:

![screenshot from 2016-12-11 12-23-34](https://cloud.githubusercontent.com/assets/6667703/21082243/3494a902-bf9d-11e6-93de-bf6cb19093e7.png)


But the other 6 themes I tested it on it works fine so I think it's the theme's problem.

**Comment by JasonLG1979** [comment]
I'd also like to reintroduce the dedicated quit and raise buttons back into the UI. I'm just not sure where yet. I'd like at least a quit button since raising can already be done.

**Comment by JasonLG1979** [comment]
Ok well I got it all wired up so that updating the settings updates the cover size either big or small which ever is currently shown in realtime. Like I said the defaults are 48px for small with a range of 32 - 96px and 192px for the large cover with a range of 128 - 256px.

Here's what it looks like with the default GNOME shell theme with a 250px large cover:
![screenshot from 2016-12-11 17-09-26](https://cloud.githubusercontent.com/assets/6667703/21084216/b89b093a-bfc5-11e6-8e4b-b0eb68c21fd7.png)

**Comment by badcel** [comment]
At least from MPRIS specification point of view there is a difference between stop and pause. So if a player does not support pausing it should set the "canPause" property to false which should result in 3 buttons only. But I think it is already implemented like this.

In pithos it looks like pause and stop is exactly the same, so the "canPause" property could be set to false ( https://github.com/pithos/pithos/blob/master/pithos/plugins/_mpris.py#L300 ), which should result in 3 buttons and not confuse the user why there are 2 functions which are doing the same thing.

I like the interface design you did :-)

Regarding the sliders perhaps there could be additional information on the playtime / volume sliders if it is hovered by the user with the mouse?

**Comment by JasonLG1979** [comment]
In Pithos Stop is mapped to Pause because there's no way to tell mpris you don't support stop. From what I remember if we set the CanPause prop to we would not be able to Pause. And since Play and Pause are the only states Pithos can be in from the users perspective that would be no good.

**Comment by JasonLG1979** [comment]
*prop to false

**Comment by JasonLG1979** [comment]
As far as there being a difference between stop and Pause in the spec, there is. But where Pause generally does the same thing in every player, Stop is a little less well defined. Stopping most of the time stops playback but what happens after you hit play after you hit stop is a bit of a wildcard.

**Comment by badcel** [comment]
You are right, most web based services only support play and pause. But unfortunately the spec is defined other way round.

The difference for the extension if canPause is set to false is, that one button to control the playback is hidden. If a service can not differentiate between different stop commands, I tend to not confuse the user with those options even if a stop means a pause, because for a web service this is more or less synonymous.

The pithos mpris client is receiving the command "stop" / "pause" from the extension if the corresponding button is hit. And if you set the "canPause" property to false, there will just never be the "pause" command received by pithos, because the pause button is never displayed by the extension. The change of "canPause" to false should not have any influence on the application itself. Just the additional button in the mediaplayer extension should vanish.

**Comment by JasonLG1979** [comment]
The problem is that this extensions behavior in that regard is inconsistent with every other mpris applet. This extension is the only applet I know of that has a stop button and if Pithos were to set CanPause to False we would loose the ability to Pause in every other applet.

**Comment by badcel** [comment]
If it would be like this, it would be a bad implementation from the other extensions, because the "canPause" property enables something additionally. The other extensions should not expect the "canPause" property to be set to true if they do not support stop and pause.

I checked the gnome and kde applet:
- Gnome checks the "canPlay" property to show the player and send the playpause command. See: https://git.gnome.org/browse/gnome-shell/tree/js/ui/mpris.js#n65
- KDE checks the "canControl" property and send the playpause command. See: https://cgit.kde.org/plasma-workspace.git/tree/applets/mediacontroller/contents/ui/main.qml#n77

So the setting of "canPause" has no influence on the mrpis clients of gnome and kde. As long as the client has the playpause function available and if the "canPlay" or "canControl" property ist set to true it will work.

**Comment by JasonLG1979** [comment]
>The other extensions should not expect the "canPause" property to be set to true if they do not support stop and pause.

They don't have stop buttons so that's not really a concern for them. To me the CanPause prop has nothing to do with stop. It simply means if you can pause or not. I would think that CanPlay would have more to do with if you can stop as play and stop or more opposite states than play and pause. In any event the Ubuntu sound menu does check the CanPause prop so it's not going to change in Pithos.

A fair compromise in my mind is to keep a list of web service players like Pithos that can't stop and hide the stop button for them.

**Comment by eonpatapon** [comment]
One use case for the stop button is web radio. If you take rythmbox and listen to a radio, CanPause will be false. With your new design there is no button to stop playing.

**Comment by badcel** [comment]
I can not test with ubuntu, but the code looks like they are checking for canPause just to send a signal to update the gui. The decision if the play/pause button is displayed only depends on the canPlay property.

Send signal: http://bazaar.launchpad.net/~indicator-applet-developers/indicator-sound/trunk.16.10/view/head:/src/media-player-mpris.vala#L293

Create gui: http://bazaar.launchpad.net/~indicator-applet-developers/indicator-sound/trunk.16.10/view/head:/src/sound-menu.vala#L328

Nevertheless I think the current way of showing / hiding the play buttons is correct. As canPause enables an additional feature in the interface , the user must be able to stop playback even if canPause is false, which requires a stop button. If the canPause property is true, it means that a player can differentiate between stop and pause and the user should see two buttons.

From my point of view the only other solution would be to remove the pause button completely and always show the stop button. This would require to ignore the canPause property, like all the other applets are doing it already.

**Comment by JasonLG1979** [comment]
Fair enough I'll put the stop button back to the way it was.

**Comment by JasonLG1979** [comment]
It would still not be a bad idea to have a list of players like Pithos that can't (really) stop like Pithos.

**Comment by eonpatapon** [comment]
Yep you can add such list

**Comment by fb87** [comment]
In the small cover mode, you're wasting a lot of space while sacrificing cover visibility. I don't understand why you want to reduce the size of the cover. Just for making the stars centered?

**Comment by JasonLG1979** [comment]
You can change the size of both the large and small cover. But IMHO it looks better centered. I don't decide the spacing between elements that's up to the theme.

**Comment by JasonLG1979** [comment]
My favorite new feature though is being able to hide the built in GNOME MPRIS controls in GNOME Shell 3.20+

![screenshot from 2017-01-02 15-48-01](https://cloud.githubusercontent.com/assets/6667703/21596641/45cdcdee-d103-11e6-9e06-2889a9ca3722.png)

**Comment by JasonLG1979** [comment]
The current settings window in my PR:
![screenshot from 2017-01-28 18-08-52](https://cloud.githubusercontent.com/assets/6667703/22400806/1248e83c-e585-11e6-9f81-86c51a6fe051.png)

The only thing it's really missing at this point is being about to set the width of popped out widget. But I'll save that for later.

**Comment by JasonLG1979** [comment]
Closed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/6b063d0b53592fc1c6a74c18ca3f8441061d7cf0
