### ISSUE TITLE
Don't display cover topBar

### ISSUE THREAD

**Issue by bissybowo** [eonpatapon/gnome-shell-extensions-mediaplayer#299]
Hi! It work great to me. Anyway could anyone tell me why the extension is unable to display any cover in the top bar ? I miss the cover since the last update. Thank you anyone.

**Comment by JasonLG1979** [comment]
This was fixed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/a5d8e3bd4cdf1df71d10ba86117a7bafe3031cab the extension just needs updating at https://extensions.gnome.org/.

**Comment by bissybowo** [comment]
The update just shows up to me. Everything works perfect. Thanks you for your reply.
