### ISSUE TITLE
Drop support for really old GNOME Shell versions?

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#306]
@eonpatapon and @badcel, this extension supports Shell versions all the way back to 3.10. The version that comes in Debian Jessie is 3.14 and 3.18 in the latest Ubuntu LTS. And Debian 9 is due for a release sometime this year.

Does anyone still use 3.10 and if so does this extension even work on 3.10?

My point is maybe we should drop support for version less than 3.18 on new releases, freeze the extension for 3.16 and drop support for versions less than 3.14 altogether?

**Comment by eonpatapon** [comment]
Yep I think I forgot to remove some versions in the metadata.json

For older versions there are branches (3.14, 3.8 etc...). What I did was creating a branch when there was a breaking change in the g-s API. For example between 3.6/3.8.

Between 3.14 and 3.16 it more a issue with CSS classes than an API change but still it would look ugly on g-s < 3.16.

The branch 3.14 is there, so it's ok to just leave versions >= 3.16 in the metadata.json.

**Comment by JasonLG1979** [comment]
Can we do a branch for 3.16 and support >= 3.18 on the main branch I run the latest stable Fedora and I keep a Ubuntu GNOME 16.04 VM around for testing. I'm unaware of any distros that run 3.16 as a LTS version? My thought is for the main branch to keep up with the Ubuntu LTS's and drop support for the Shell version in the previous LTS when the current LTS hits xx.xx.1. So for example when 18.04.1 is released we would drop support for 3.18 (16.04/16.04.x) and set the minimum version in the main branch to whatever the version that comes with 18.04 . As we drop support we would create a legacy branch for people to do bug fixes only.

**Comment by eonpatapon** [comment]
Ok, so we don't have any way to test the current code on 3.16 ? I'm ok to make a branch for 3.16 but it would be nice to test if the code is ok on 3.16 :)

**Comment by JasonLG1979** [comment]
I can see which ancient version of Ubuntu came with 3.16 and throw it in a VM real quick I guess? It's kinda moot point though that version would have already reached EOL by now...

**Comment by JasonLG1979** [comment]
Of the big parent distros that most distros are based on:

Debian 3.14 - way old not interested in supporting 3.14
Ubuntu 16.04 - 3.18
Fedora 24 & 25 - 3.18, 3.20
Arch - the absolute latest version, it's Arch,lol!!!
OpenSuse - ? 3.18 at least I'd think?
