### ISSUE TITLE
Create a wiki

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#308]
The readme is huge. A wiki would be helpful. For example it could offer help and guidance for devs that want to correctly implement the MPRIS interfaces.

**Comment by JasonLG1979** [comment]
@eonpatapon I can't create the initial wiki. If you do that I can add wiki pages and move some of the cluttered readme to wiki pages.

**Comment by JasonLG1979** [comment]
Still waiting on the wiki @eonpatapon. I'd also like to add a section for would be player devs that want to add MPRIS support for their player. Sort of a do's and do not's. Like Do emit prop changes. Do Not emit redundant prop changes and so on.

**Comment by eonpatapon** [comment]
Sure, I've enabled the wiki

**Comment by JasonLG1979** [comment]
Awesome thanks!!!
