### ISSUE TITLE
GNOME completely freezes when using Spotify

### ISSUE THREAD

**Issue by bulletmark** [eonpatapon/gnome-shell-extensions-mediaplayer#313]
Since the last update on extensions.gnome.org, starting Spotify, or any new track on Spotify, causes GNOME to completely freeze for at least 2 seconds. Mouse won't move, keyboard does not work, clock seconds stop, etc. Disabling this extension makes the problem go away.

I played with the settings but no matter what I turn off, or on, makes any difference.

I am on up-to-date Arch Linux X64 with `gnome-shell 3.22.2+18`. I rolled back a few versions of the spotify client but made no difference.

**Comment by JasonLG1979** [comment]
Is it just Spotify? Do other apps work fine? What do the logs say?

**Comment by bulletmark** [comment]
All other music players are fine, nothing in journal.

**Comment by bulletmark** [comment]
Note there is a comment on extensions.gnome.org from another guy who reported this problem there before I did.

**Comment by JasonLG1979** [comment]
> Note there is a comment on extensions.gnome.org from another guy who reported this problem there before I did.

That's not the place to report bugs...

**Comment by bulletmark** [comment]
Yes, I know. But most people don't know about github so you can't blame them.

**Comment by JasonLG1979** [comment]
If there's nothing in the logs and it works with everything else. I'd say it's a Spotify problem. I'll have to take a peak at their source code (if I can?). Spotify has notoriously crappy MPRIS support.

**Comment by bulletmark** [comment]
Spotify worked fine with this extension before that last update.

**Comment by JasonLG1979** [comment]
The only thing I can think of is the last update adds a check to validate cover image file before we try to use it. If I had to guess they are providing a remote file for the MPRIS cover image instead of caching it locally 1st. I can bypass the check for remote images but it kinda defeats the purpose. They really shouldn't be using remote images...

**Comment by bulletmark** [comment]
Please tell me the line of code to disable so I can confirm this.

**Comment by JasonLG1979** [comment]
Change this:
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/ui.js#L454-L461

To this:
```js
    else if (state.trackCoverUrl) {
      let file = Gio.File.new_for_uri(state.trackCoverUrl);
      let gicon = new Gio.FileIcon({file: file});
      coverIcon = new St.Icon({gicon: gicon, style_class: "track-cover",
                               icon_size: this.trackCover.child.icon_size});
    }
```

And either disable covers in the panel for now for testing or change this:
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/panel.js#L114-L119

To This:
```js
  this._primaryIndicator.gicon = new Gio.FileIcon({file: file});
```

**Comment by bulletmark** [comment]
Sorry, new to extensions. On Wayland, even though I off/on the extension through tweak tool, it seems to be cached somewhere. How do I force reload?

**Comment by JasonLG1979** [comment]
You have to logout and log back in to restart the Shell with Wayland, possibly even restart. Alt+F2 -r doesn't work in Wayland.

**Comment by bulletmark** [comment]
Actually this works well https://nls1729.github.io/extension-reloader.html.

**Comment by JasonLG1979** [comment]
Ok, whatever works.

**Comment by bulletmark** [comment]
Yes, making those code changes makes the problem go away.

**Comment by JasonLG1979** [comment]
I installed Spotify. I'll investigate.

**Comment by JasonLG1979** [comment]
Ok, I'll revert the check maybe just change it to a try, catch?

**Comment by bulletmark** [comment]
Thanks. Ping me here to test out any pre-release branch if you want.

**Comment by JasonLG1979** [comment]
Will do.

**Comment by JasonLG1979** [comment]
Here this should do it. I ended up just scrapping the check all together as much as I hate to. The methods that creates the cover icon doesn't return an error if an invalid image uri so I can't even do a try, catch...

https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/tree/remote-cover-uri-fix

**Comment by bulletmark** [comment]
I installed latest master branch from this repo and the problem is fixed.

**Comment by JasonLG1979** [comment]
> I installed latest master branch from this repo and the problem is fixed.

Good to hear. I initially added the check because at least one player sends invalid/malformed file uri's. Seriously, half the extension's source is checking and working around improper MPRIS implementations.

**Comment by bulletmark** [comment]
I prefer to run released extensions.gnome.org versions. Can I ask what the ETA would be for the fix to get there?

**Comment by JasonLG1979** [comment]
I don't hand that, but we can put a bug in @eonpatapon ear to update it. :D

**Comment by ItayXD** [comment]
Thank you very much for this fix! I had no idea what was causing it but it made spotify unusable

**Comment by JasonLG1979** [comment]
Someone should file a bug report with them. They should cache their image for MPRIS. My guess is that they don't use cached local images for desktop notifications either which is also a No, No...

**Comment by JasonLG1979** [comment]
@bulletmark can you comment on the extension page that it has been fixed and is awaiting updating. @eonpatapon can you put a note in the description to report bugs at github not in the comments?

**Comment by bulletmark** [comment]
Done, comment added at https://extensions.gnome.org/extension/55/media-player-indicator/

**Comment by eonpatapon** [comment]
I've uploaded the current master on e.g.o

**Comment by bulletmark** [comment]
I updated via e.g.o and all good. Thanks!
