### ISSUE TITLE
metadata: null instead of "Unknown"

### ISSUE THREAD

**Issue by roizcorp** [eonpatapon/gnome-shell-extensions-mediaplayer#318]
hi,

I'm not sure this is a valid use case for everyone but my library is built as full albums alongside individual songs: the songs part of albums contain the "date" and the "album title" while the individual songs do not.

I wish the media indicator will not show anything in case if no value is set in the metadata (currently it says: "Unknown Name"

**Comment by JasonLG1979** [comment]
That's common practice. That's coming from your player not us. If it were coming from us, i.e. your player did not provide a album title it would read "Unknown album" for no album title metadata.
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/player.js#L436

You can fix that with a tag editor or editing the metadata in your player I'd imagine.

**Comment by roizcorp** [comment]
This is exactly what the issue is about, in case where there is no value in a given metadata, the indicator places "Unknown <metadata>", and I wish for setting to set it as null instead...

Anyways thanks to your reference I changed .js file myself. Now how about a prefix/suffix in case there is a value e.g. 
<album name> = null -> ""
<album name> != null -> "from <album name>"

**Comment by JasonLG1979** [comment]
What I'm trying to tell you is if you're getting what you say you are it's not coming from us but the player. The player is sending "Unknown Name" to the extension. As I said that is common practice.

**Comment by roizcorp** [comment]
The player is MPD, The value is null, MPD sends nothing (so the indicator places "Unknown property", in fact, since I changed the .js it works exactly as expected.

**Comment by JasonLG1979** [comment]
I'm not sure how you were getting "Unknown Name" then if it's not send by the player since that's no where in our code?

**Comment by roizcorp** [comment]
it is not explicity "Unknown Name" it was "Unknown Album" like your referred in your .js code.

**Comment by JasonLG1979** [comment]
OK well I'm going to close this you seem to have figured it out.
