### ISSUE TITLE
Display file name if no metadata

### ISSUE THREAD

**Issue by muffinmad** [eonpatapon/gnome-shell-extensions-mediaplayer#321]
Better to display file name instead of "Unknow artist - Unknonw title"

**Comment by JasonLG1979** [comment]
That's standard behavior, We're just following GNOME Shell's default behavior (and other applet/clients?) we're not going to parse the file name. If you don't like  "Unknown artist - Unknown title" then either update the metadata of the source music files or if there is the correct metadata file a bug with the player. If you're seeing that it means that the player is not sending any artist or title metadata.

**Comment by muffinmad** [comment]
Ok, i see.
As for other clients, mpc, for example, has nice output format operators.

The [] operator is used to group output such that if no metadata delimiters are found or matched between '[' and ']', then none of the characters between '[' and ']' are output. '&' and '|' are logical operators for and and or.

Some useful examples for format  are: "[[%artist% - ]%title%]|[%file%]".

I will be glad to see support for this format.

Thanks!

**Comment by JasonLG1979** [comment]
We follow the mpris spec. If a player also follows the spec it will work. If it doesn't work it's a bug on the player's part.
