### ISSUE TITLE
different license version

### ISSUE THREAD

**Issue by martinkg** [eonpatapon/gnome-shell-extensions-mediaplayer#323]
the package's included COPYING file that is a copy of the GPLv2.
Version 3 might be more accurate, because the license comment at the top of widget.js says version 3,
which should therefore apply to the whole project.

**Comment by JasonLG1979** [comment]
It looks like a typo. Both licencees were added at the same time by @eonpatapon. So which is it @eonpatapon 2 or 3? I really don't personally care which you choose. (what limited code I've written on my own elsewhere I've released under a v3 licence.) for this project there's really no danger of " Tivoization" so from a practical standpoint there's really no difference between the 2.
