### ISSUE TITLE
rpmlint reports: Packages should try to preserve timestamps of original installed files.

### ISSUE THREAD

**Issue by martinkg** [eonpatapon/gnome-shell-extensions-mediaplayer#324]
might you consider editing the Makefile to use `cp -p` or `install -p` or equivalent.

**Comment by JasonLG1979** [comment]
PR's are welcome. There's a lot that could be done to improve the extension. I know really nothing of make.

**Comment by terrycloth** [comment]
A Makefile is basically just a collection of shell scripts. Preserving file timestamps is simply a matter of adding an option to the `cp` commands. You could do a find-and-replace on `Makefile.am`, searching for all instances of `cp` and replacing with `cp --preserve=mode,timestamps` or the more succinct `cp -p`.

`zip`, I believe, already preserves file timestamps.

**Comment by JasonLG1979** [comment]
Again, PR's are welcome, make isn't that interesting to me. I'd much rather play with the UI bits of the extension. the install works just fine for me(again not really caring that much about make) if it's something that bothers you please feel free to put in a PR with your changes.
