### ISSUE TITLE
GNOME 3.24

### ISSUE THREAD

**Issue by JasonLG1979** [eonpatapon/gnome-shell-extensions-mediaplayer#338]
GNOME 3.24 was released today. The current master should be good to go for 3.24. I've been testing it on Ubuntu 17.04 for a couple weeks. @eonpatapon you just need to throw it up on the shell extensions site.

**Comment by eonpatapon** [comment]
Ok, should we update the minimal version to 3.18 ?

**Comment by JasonLG1979** [comment]
That would be ideal IMHO.

**Comment by eonpatapon** [comment]
Done
