### ISSUE TITLE
Add support for setting Quod Libet rating

### ISSUE THREAD

**Issue by IBBoard** [eonpatapon/gnome-shell-extensions-mediaplayer#341]
Based on [the code](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/c3dff43f859873a73491dc544001c481ded0d031/src/widget.js#L406-L409) then ratings are set by calling commands rather than using MPRIS interface (because setting ratings isn't part of the spec).

I've moved from Banshee to Quod Libet, and the extension now doesn't support setting the rating. Quod Libet supports [setting ratings via the CLI](https://quodlibet.readthedocs.io/en/latest/guide/commands/quodlibet.html?highlight=set-rating), so a matching method could be used (with a score of 0.0 to 1.0)

**Comment by JasonLG1979** [comment]
@IBBoard Adding support for setting ratings is generally either done by the developer of the player or other interested parties, not by us(unless we're the interested party ofc) Basically if you want that added you'll have to add it yourself or find someone who will.

**Comment by IBBoard** [comment]
Done 😊

(Although Quod Libet allows ratings other than 1-5 stars, but that's another matter!)

**Comment by JasonLG1979** [comment]
Closed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/c149c06bfc7e776388b87489bd201fcc30d4af6e

**Comment by JasonLG1979** [comment]
@IBBoard I put in a bug report for what I said above and noted it in the wiki under Known Player Bugs.

https://github.com/quodlibet/quodlibet/issues/2358
