### ISSUE TITLE
CanSeek not respected

### ISSUE THREAD

**Issue by saivert** [eonpatapon/gnome-shell-extensions-mediaplayer#344]
This extensions doesn't seem to respect CanSeek or checks it too late.
It sometimes shows the seekbar and sometimes not.
Especially if you click play from the mpris client.
Checking with D-Feet shows the correct value.

I notice other players like Quod Libet always return true for this property regardless if playing internet radio or not.

I'm implementing CanSeek handler for deadbeef's mpris2 plugin and stumbled upon this issue.

**Comment by JasonLG1979** [comment]
It shouldn't need to check at all. It's up to the player to emit property changed signals anytime a property changes. It's also up to the player to make sure they don't put up an empty interface. All properties should have at least dummy/default values upon interface creation. And then you would update us by sending the real value in the prop changed signal.

But the the slider is not shown or hidden by that prop.

**Comment by saivert** [comment]
But this extension does query other properties.

**Comment by JasonLG1979** [comment]
> But this extension does query other properties. The whole mpris design is screwy and nobody seems to follow spec.

That's why it does. By spec it shouldn't have to. Uh and I almost for got. CanSeek doesn't control the visibility of the slider it only controls if it can be interacted with.  The visibility of the slider is determined by if a player can give us a valid position and duration. You could set CanSeek to false and as long as we get a position and duration the slider will be shown. https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/732a6e6ce83d5c47632171b0c72116d3e5935ef2

**Comment by JasonLG1979** [comment]
Edit: It's been a while, I guess all you need is a duration and you get the slider.

**Comment by saivert** [comment]
Problem is if I return false for CanSeek (when queried, not emitted), this extension doesn't show the seekbar even if duration > 0. So is this a bug in deadbeef's mpris plugin or in this gnome-shell extension?

**Comment by JasonLG1979** [comment]
What version of the extension are you using?

**Comment by saivert** [comment]
Latest on extensions.gnome.org

**Comment by JasonLG1979** [comment]
Build from git and see if that helps. I'm not sure when that was last updated.

**Comment by JasonLG1979** [comment]
Yep. It's a bug on our part. CanSeek *shouldn't* have anything to do with it but it does. I'll see what I can do.

**Comment by JasonLG1979** [comment]
@saivert narrowed it down. The fix is pretty simple for well behaved implementations but I'm currently trying to work around Spotify's  absolute SH!T MPRIS implementation.

 https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/MPRIS-Implementation-is-severely-broken-in-the-Linux-client/td-p/1661880

**Comment by JasonLG1979** [comment]
I think the solution is to never show the position or volume slider with spotify since neither actually work...

**Comment by JasonLG1979** [comment]
Or ratings or the stop button. As ratings don't work and stop is actually mapped to pause...

**Comment by JasonLG1979** [comment]
@saivert Try this branch I think it fixes the problem for well behaved players. And makes it easier to knock misbehaving players down a peg.

https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/tree/handle-spotify

**Comment by saivert** [comment]
Yes it shows the seekbar consistently now but seeking doesn't always work.
At least with deadbeef's mpris. Quod Libet just always let you seek even if no track is playing (it will just resume at the new seeked location when you hit play). Different players implement mpris differently. It is a mess. I think the spec allows too much freedom.

**Comment by JasonLG1979** [comment]
> Yes it shows the seekbar consistently now but seeking doesn't always work.
> I have verified with D-Feet that CanSeek returns true and that metadata has a valid length property. Yet this extension doesn't let me seek.
> 
> At least with deadbeef's mpris. Quod Libet just always let you seek even if no track is playing (it will just resume at the new seeked location when you hit play). Different players implement mpris differently. It is a mess. I think the spec allows too much freedom.

Are you emitting a prop change signal?

**Comment by saivert** [comment]
Seeking works when starting playback of a new track. If I hit stop and then play again seeking doesn't work. I guess a new propchange has to be emitted every time you start playback.

**Comment by JasonLG1979** [comment]
It works like this. When an interface becomes available it checks the props. If the props aren't available at interface creation defaults are assumed. The assumed default for CanSeek is false.

Props are also queried at each track change. So you you need to keep that CanSeek value around for the extension to query. Any time you change the value emit a change. You don't need to emit a bunch of prop changes at the start of every song though.

**Comment by JasonLG1979** [comment]
I'll do some more testing but the intention is for the CanSeek prop to only set the re-activeness of the slider. Basically false equals you can't move it and true equals you can.

**Comment by JasonLG1979** [comment]
The only prop change you need to emit at a song change is the metadata. That's how we tell the song has changed. If nothing else has changed don't emit anymore changes. You don't even need to emit a playstate change going from track to track unless you're going to pause or stop. normally though you would stay in play if one track plays right after the next.

**Comment by JasonLG1979** [comment]
Seems to work as expected in my tests. I modified Pithos to tie the playstate with canSeek(for testing not that you should do that) so that if it wasn't playing you could not seek and if you were playing you could seek. As i said it worked as expected. Pause Pithos the slider is not reactive play Pithos it is reactive.

**Comment by JasonLG1979** [comment]
Normally in Pithos we lie and always say we can seek so the slider is displayed in other clients that also depend on CanSeek to tell when to show the slider. We can't ever really ever seek so we short circuit the SetPosition method and send a seeked signal with the current position. The effect is that if you grab the slider it always just snaps to the current position.

**Comment by saivert** [comment]
There is some bugs with the code that checks track duration in my CanSeek property getter. If I always return TRUE it works as expected and the gnome-shell extension only shows seekbar if duration > 0.

**Comment by JasonLG1979** [comment]
For the sake of simplicity and to make sure the pos slider is visible in most clients you could do something similar.

always return true from the CanSeek prop and inside the SetPosition emit a seeked signal with the current position if you can't actually seek at that moment or if you can seek and emit the seeked signal with where you seeked to. No matter what after the SetPosition method is called you're expected to emit a seeked signal with the position of where you seeked too.

**Comment by JasonLG1979** [comment]
> AFAIK the mpris client is responsible for querying the other properties.

No. It's DBus. You are responsible for emitting prop all changes clients are suppose to be passive listeners.

**Comment by JasonLG1979** [comment]
That's how props work. How would you expect a client to know when you changed a prop? Are we suppose to have a polling loop?

**Comment by saivert** [comment]
Right after playback starts this happens:

MPRIS Debug Info: DB_EV_TRACKINFOCHANGED event received
MPRIS Debug Info: Get property call on Player interface. sender: :1.3958, propertyName: Position
MPRIS Debug Info: Get property call on Player interface. sender: :1.3958, propertyName: CanSeek
MPRIS Debug Info: Get property call on Player interface. sender: :1.3958, propertyName: CanPause
MPRIS Debug Info: Get property call on Player interface. sender: :1.3958, propertyName: CanGoNext
MPRIS Debug Info: Get property call on Player interface. sender: :1.3958, propertyName: CanGoPrevious
MPRIS Debug Info: Get property call on root interface. sender: :1.3958, propertyName: HasTrackList

**Comment by JasonLG1979** [comment]
> Right after playback starts this happens

That's because most implementations are broken in one way or the other. We check at the beginning of songs because if we didn't 1/2 the players out there wouldn't work. With Pithos, because we do things right, the extension would NEVER actually have to actively check anything EVER.

**Comment by JasonLG1979** [comment]
Just because everyone else does it doesn't mean it's right.

**Comment by saivert** [comment]
After the initial query, CanSeek doesn't change or shouldn't. D-Feet verifies it returns the right value.
Yet when I click stop and then play again,. Seekbar is unreactive as if CanSeek suddenly returned false (which it didn't).

**Comment by JasonLG1979** [comment]
Where's the code?

**Comment by saivert** [comment]
https://github.com/Serranya/deadbeef-mpris2-plugin

**Comment by JasonLG1979** [comment]
I think I might see your problem. CanSeek depends on if you have a duration correct? Do you always know the track duration when tracks change?

**Comment by JasonLG1979** [comment]
d-feet is going to tell you what the value is now by querying the value not what it was when the extension asked for it. I bet it returns false to the extension. debug that prop.

**Comment by JasonLG1979** [comment]
Unless you're pre-calculating duration many player engines (Gstreamer for example) don't actually know the track duration until just after they start playing it.

**Comment by JasonLG1979** [comment]
In Pithos we get around that by using the position provided by Pandora which is not always correct. Then when Gstreamer actually figures out the actual duration we send another metadata change signal with the correct duration. That way we always have something to hand to MPRIS.

**Comment by saivert** [comment]
Think I fixed it by doing this:

```diff
diff --git a/src/mprisServer.c b/src/mprisServer.c
index 16a41e7..e614729 100644
--- a/src/mprisServer.c
+++ b/src/mprisServer.c
@@ -626,9 +626,10 @@ void emitMetadataChanged(int trackId, struct MprisData *userData) {
 	g_variant_builder_unref(builder);
 }
 
-void emitPlaybackStatusChanged(int status) {
+void emitPlaybackStatusChanged(int status, struct MprisData *userData) {
 	if (!globalConnection) return;
 	GVariantBuilder *builder = g_variant_builder_new(G_VARIANT_TYPE_ARRAY);
+	DB_functions_t *deadbeef = ((struct MprisData *)userData)->deadbeef;
 
 	switch (status) {
 		case OUTPUT_STATE_PLAYING:
@@ -642,6 +643,19 @@ void emitPlaybackStatusChanged(int status) {
 			g_variant_builder_add(builder, "{sv}", "PlaybackStatus", g_variant_new_string("Stopped"));
 			break;
 	}
+
+	gboolean can_seek = FALSE;
+	DB_output_t *output = deadbeef->get_output();
+	if (output) {
+		DB_playItem_t *track = deadbeef->streamer_get_playing_track();
+		if (track) {
+			can_seek = deadbeef->pl_get_item_duration(track) > 0;
+			deadbeef->pl_item_unref(track);
+		}
+	}
+	g_variant_builder_add(builder, "{sv}", "CanSeek", g_variant_new_boolean(can_seek));
+
+
 	GVariant *signal[] = {
 		g_variant_new_string(PLAYER_INTERFACE),
 		g_variant_builder_end(builder),
```

**Comment by JasonLG1979** [comment]
> Think I fixed it

Cool, glad to hear!!! Confirm that it works and I'll merge that branch into master.

**Comment by JasonLG1979** [comment]
I have zero C foo. What was the problem?

**Comment by saivert** [comment]
In addition to playback status it is now also emitting CanSeek property changes.
This is for the deadbeef mpris plugin of course.

And yes you can close this issue as handling in the mpris client works well now according to my testing.

**Comment by JasonLG1979** [comment]
Awesome!!!
