### ISSUE TITLE
Allow hiding of icon when in system menu

### ISSUE THREAD

**Issue by cra0zy** [eonpatapon/gnome-shell-extensions-mediaplayer#345]
It would be nice if there was a way to not display the indicator icon when you set its position to system menu.

**Comment by JasonLG1979** [comment]
Which Icon? If no player is active the panel icon is not shown. If the allow starting of default player setting is turned off no icon is shown in the system menu if there is no active player.

**Comment by cra0zy** [comment]
I don't want it shown ever, even when the player is active, it represents no useful information.

![icon](https://cloud.githubusercontent.com/assets/6773302/25255686/482e623c-262c-11e7-8684-8f01c67900a5.png)

**Comment by JasonLG1979** [comment]
OK, no problem I'll see what I can do. Shouldn't be much trouble to put a user setting in for that. I work on that this weekend.

**Comment by cra0zy** [comment]
Sweet :D

**Comment by JasonLG1979** [comment]
It'll probably be something like "Hide Panel Icon when in System Menu". It will ofc default to false and will have no effect if the position is not System Menu otherwise there's no way to interact with the extension,lol!!!

**Comment by JasonLG1979** [comment]
@cra0zy I haven't forgot about you. I have a another PR pending then I'll implement your request.

**Comment by cra0zy** [comment]
![the-north-remembers-gif](https://cloud.githubusercontent.com/assets/6773302/25411783/f9b3126e-2a1e-11e7-94c2-19d193865f7a.gif)

**Comment by JasonLG1979** [comment]
I'm more Midwest Actually,lol...

**Comment by JasonLG1979** [comment]
But I guess if you go northern vs southern states, I am what my cousins in Mississippi would call a "Yankee",lol!!! Being from and living in Iowa my whole life...

**Comment by JasonLG1979** [comment]
@cra0zy test this branch out. https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/tree/never-show-agg-menu-indicator-option

**Comment by JasonLG1979** [comment]
If it checks out with you I'll test it on my Ubuntu 17.04 VM, easiest way to test on GNOME 3.24. 3.24 has a stricter js engine so code that works just fine in 3.22(what I'm on Fedora 25) may throw exceptions in 3.24.

**Comment by JasonLG1979** [comment]
Well I went a head and merged that and tested it on GNOME 3.24. It seems to work as expected.

**Comment by cra0zy** [comment]
It works \o/

Tho I must critic you on your makefile script which wants to install the extension in the system /usr directory instead of making use of .local/share/gnome-shell/extensions directory. The later allows updating from the website as well.

**Comment by JasonLG1979** [comment]
> Tho I must critic you on your makefile script which wants to install the extension in the system /usr directory instead of making use of .local/share/gnome-shell/extensions directory. The later allows updating from the website as well.

I know nothing of the make file, that's not me. Although I believe you can change that maybe by passing an option?

**Comment by JasonLG1979** [comment]
Anyway that's a separate issue feel free to file a issue about that. I'm going to close this as your initial issue has been solved.
