### ISSUE TITLE
Installing error help please

### ISSUE THREAD

**Issue by tjw0lf** [eonpatapon/gnome-shell-extensions-mediaplayer#353]
Making all in src
make[1]: Entering directory '/home/tj/Downloads/gnome-shell-extensions-mediaplayer-master/src'
Makefile:501: *** missing separator.  Stop.
make[1]: Leaving directory '/home/tj/Downloads/gnome-shell-extensions-mediaplayer-master/src'
Makefile:350: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by JasonLG1979** [comment]
Install instructions are in the wiki. And please don't create wiki pages asking for help.

The short version of how to install is:

Clone the git repo:

git clone https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer.git
cd gnome-shell-extensions-mediaplayer

Install System-wide:

./autogen.sh
make
sudo make install

Or In your ~/.local directory:

./autogen.sh
make install-zip

**Comment by tjw0lf** [comment]
I did this one.
Install System-wide:

./autogen.sh
make
sudo make install

And got that error  i posted?

**Comment by JasonLG1979** [comment]
What distro? Do you have all the dependencies installed?

**Comment by tjw0lf** [comment]
Ubuntu GNOME 17.04.

I have all of these ones
automake, gnome-common, gettext

not to sure which ones these are glib2 devel files. in synaptic package manager

**Comment by JasonLG1979** [comment]
I'm not a Ubuntu user. But I'd say start with libglib2.0-dev

**Comment by tjw0lf** [comment]
Thanks it must have been a dependencie. i installed glib2 dev also was going throug the closed threads and found the commands i needed. I just deleted the folder it was in and re git it And worked like charm now.

**Comment by JasonLG1979** [comment]
@eonpatapon if you haven't already can you lock the wiki so that only contributors can edit it?
