### ISSUE TITLE
Close the mediaplayer app to the extension

### ISSUE THREAD

**Issue by WyRe** [eonpatapon/gnome-shell-extensions-mediaplayer#354]
I would consider that feature, I would like can close the app without stop it.

**Comment by JasonLG1979** [comment]
That's beyond what we can do. We don't have control of the app we're just using what's available over DBus(the MPRIS spec) that would be something you'd want to take up with the devs of your chosen player.

**Comment by JasonLG1979** [comment]
Even if a dev of whatever player were to consider your request there's no (non-hacky) way for said player to know that anything was actually listening to/using the MPRIS interface(s).  The risk is that you could end up loosing the window if the player assumed a MPRIS client and there wasn't one.
