### ISSUE TITLE
click on albumart is expected to open player

### ISSUE THREAD

**Issue by corebots** [eonpatapon/gnome-shell-extensions-mediaplayer#355]
please would you consider an option to show large albumart and open the player when one clicks on it - instead of switching between large/small sized albumart on clicks. lots of people at my pc ask me how to open the player when clicking is zooming the cover only ;) thank you, great extension!

**Comment by JasonLG1979** [comment]
If you click just about anywhere *but* the album cover it raises the player. But I have though about getting rid of the whole cover zooming thing altogether and just have a pref that sets the layout vertical or horizontal. Another option I also like is make left click raise the player and right click zoom.

**Comment by corebots** [comment]
Thanks for the suggestion, i use the 'click around the albumart' way myself, and got used to it already - it's just that it isn't really an intuitive solution as I've find the people interacting with my pc to only click on the picture. 

I like the larger size cause then more text (song info) fits underneath, but the way you describe it would be also nice - different behavior for right and left click... 

Would there be a way how to easily adjust the code to keep one size and always rise the player on click?

Anyways, I'm looking forward to further updates ;) keep up the good work!

**Comment by JasonLG1979** [comment]
> Thanks for the suggestion, i use the 'click around the albumart' way myself, and got used to it already - it's just that it isn't really an intuitive solution as I've find the people interacting with my pc to only click on the picture.

I agree, it's not very intuitive. IMHO left click should raise the player. I'm working on it right now. The problem I'm trying to solve ATM is that the cover is a button and will only register left clicks as far as I can tell. I'll see if the box behind it will register a right click and just bind to it? 

> I like the larger size cause then more text (song info) fits underneath, but the way you describe it would be also nice - different behavior for right and left click...

I prefer the large cover view myself.

> Would there be a way how to easily adjust the code to keep one size and always rise the player on click?

With a little tweaking of the toggle function. Shouldn't be to hard.

> Anyways, I'm looking forward to further updates ;) keep up the good work!

Should have something in a day or 2. thanks!!!

**Comment by JasonLG1979** [comment]
There @corebots https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/8d3a94e851e8bc37fb3127df7ff7d14b7468cc13 Gives you 2 new user settings one allows you to set it so that clicking the cover raises the player the other starts the player with the large cover.

**Comment by corebots** [comment]
Thank you @JasonLG1979 for the fast _fix_, this seems to work really good :)

**Comment by JasonLG1979** [comment]
@corebots no problem I've been meaning to add the start zoomed option for a while now anyway. Glad it solved your problem. I'm going to close this issues because you seem happy with the solution.

**Comment by JasonLG1979** [comment]
@corebots https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/8d3a94e851e8bc37fb3127df7ff7d14b7468cc13 fixes a bug where sometimes the song text was not showing up when starting with the large cover(zoomed) so if you see that it should be fixed.
