### ISSUE TITLE
Weird behaviour with track seeking

### ISSUE THREAD

**Issue by SubhamSatyajeet** [eonpatapon/gnome-shell-extensions-mediaplayer#359]
When I enable the track seeker in the Extension settings, the track seeker shows for a particular song. If I turn off the player and switch it back on, the track seeker is gone. This happens with Clementine and Rhythmbox.

(Clementine only) after the track seeker has vanished, when I click pause on a song, it appears then and there. This happens only after I open a playlist directly from the media player indicator.

Ubuntu Gnome 16.04 LTS
Gnome Shell 3.18.5
Clementine 1.3.1

**Comment by JasonLG1979** [comment]
Ok I'll look into it.

**Comment by JasonLG1979** [comment]
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/a50e1b86bfbccbdad48b10ce18617c72aeb7aa01

Seems to fix the issue for me. @SubhamSatyajeet can you test the latest git and let me know it it fixes it for you?

**Comment by SubhamSatyajeet** [comment]
I tried installing the git folder manually, as mentioned in the program wiki, but the command `make install` showed errors.

**Comment by JasonLG1979** [comment]
You mean sudo make install? You need to install all of the dependencies.

**Comment by SubhamSatyajeet** [comment]
Yes, I tried `sudo make install` as well, it shows the same error that I showed above.

**Comment by JasonLG1979** [comment]
You have not installed all of the dependencies

**Comment by JasonLG1979** [comment]
I will add Ubuntu/Debian and Fedora specific install instructions to the wiki.

**Comment by JasonLG1979** [comment]
```sudo apt-get install git automake gnome-common gettext libglib2.0-dev``` to install the dependencies for Ubuntu.

**Comment by SubhamSatyajeet** [comment]
Got it working. Thanks!

That last one: `libglib2.0-dev` was listed as glib devel. I'd gotten confused, my bad.
It worked. A funny side effect now is that the icon for the extension isn't showing up until I start my media player. Is that supposed to happen in the newer version?

**Comment by JasonLG1979** [comment]
The ability to launch players from the extension has been removed from the master branch for that reason. It's buggy and in my opinion redundant.

**Comment by JasonLG1979** [comment]
@SubhamSatyajeet did that solve the issue?

**Comment by JasonLG1979** [comment]
> That last one: libglib2.0-dev was listed as glib devel. I'd gotten confused, my bad.

glib devel is the upstream name. Debian likes to rename packages for whatever reason.

**Comment by SubhamSatyajeet** [comment]
The issue is solved, thank you!
