### ISSUE TITLE
Cannot start media player from the extension

### ISSUE THREAD

**Issue by matteotanca** [eonpatapon/gnome-shell-extensions-mediaplayer#367]
I click the media player icon  but it doesn't start.

I'm on Ubuntu Gnome 17.04 with Gnome 3.24.1

**Comment by JasonLG1979** [comment]
The ability to launch players from the extension has been removed from the master branch for that reason. It's buggy and in my opinion redundant.

The extension needs updating on the GNOME extensions site.

**Comment by AmirHosseinKarimi** [comment]
Is there any option to give back this feature? (launch from menu & always show indicator)

**Comment by JasonLG1979** [comment]
No. seee: https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/367#issuecomment-303117859
