### ISSUE TITLE
trackTitle syntax just displays "trackTitle"

### ISSUE THREAD

**Issue by DrDoctor13** [eonpatapon/gnome-shell-extensions-mediaplayer#382]
![screenshot from 2017-05-28 23-20-45](https://cloud.githubusercontent.com/assets/11695921/26535534/6d35127c-43fc-11e7-928d-e5e4de28c4a1.png)

Using with gpmdp (Google Play Music Desktop Player)

**Comment by JasonLG1979** [comment]
Latest git?

**Comment by JasonLG1979** [comment]
You forgot the curly brackets around the keys.

**Comment by DrDoctor13** [comment]
I just discovered that. Didn't get the impression brackets were needed from wiki page.

**Comment by JasonLG1979** [comment]
My bad I've been trying to update the wiki. Just changed it. I also just added {playerName} as a placeholder today.
