### ISSUE TITLE
Queue management

### ISSUE THREAD

**Issue by joshtriplett** [eonpatapon/gnome-shell-extensions-mediaplayer#56]
I use this extension with Quod Libet.  I'd love to manage Quod Libet's queue directly from the music menu: display the contents of the queue, allow deleting or reordering items in it, allow switching to a song in it, allow toggling the "random" queue order, and (based on issue 55) allow adding new songs to it.

**Comment by eonpatapon** [comment]
Closing this, as said before, TrackList support won't happen anytime soon.
