### ISSUE TITLE
rtl-mode does not work correctly

### ISSUE THREAD

**Issue by ConvMe** [eonpatapon/gnome-shell-extensions-mediaplayer#81]
When switching my language into a right-to-left language the whole desktop mirrors. For some reasons the media buttons of the extensions does not fit anymore into the popup-window. I also tested with default gnome 3.4.1 theme.

**Comment by JasonLG1979** [comment]
@haimn, @haimnaf, @ConvMe or @eonpatapon is this still an issue?

**Comment by JasonLG1979** [comment]
I'm going to assume this is no longer a problem since there are no follow ups.
