### ISSUE TITLE
DBus interface similar to Ubuntu Sound Menu

### ISSUE THREAD

**Issue by fenryxo** [eonpatapon/gnome-shell-extensions-mediaplayer#85]
Ubuntu Sound Menu provides DBus interface that allows media player to check whether the sound menu is present and whether the media player is shown in the menu (i.e. it isn't blacklisted).

Media player can use this information to be sure that it can hide the main window, when a close button is pressed, and the hidden window can be reactivated from the sound menu. Otherwise, it can provide alternative ways how to reactivate the window (e.g. tray icon).

I would like to see similar (preferably identical) DBus interface in this extension to get rid of unnecessary tray icon that only duplicates functionality already provided by this excellent extension.

Ubuntu Sound Indicator DBus service has name "com.canonical.indicators.sound", path "/com/canonical/indicators/sound/service" and interface "com.canonical.indicators.sound". The API is described in http://bazaar.launchpad.net/~indicator-applet-developers/indicator-sound/trunk.12.10/view/head:/src/sound-service.xml

**Comment by Wabuo** [comment]
+1

**Comment by JasonLG1979** [comment]
Closing this. See #249. You can check gsettings to see if the extension is installed and enabled.
